import type { ModuleManifest } from '../../core/types/module';

export const projectManifest: ModuleManifest = {
  id: 'concrete.project',
  name: 'Project Management',
  description: 'Project scheduling, Gantt charts, CPM, EVM, daily logs, RFIs, submittals, meeting minutes, weather delays, and resource loading',
  version: '1.0.0',
  phase: 18,
  dependencies: ['concrete.job'],
  collections: [
    'project/project', 'project/milestone', 'project/task',
    'project/taskDependency', 'project/dailyLog', 'project/rfi',
    'project/submittal', 'project/meetingMinutes', 'project/weatherDelay',
    'project/resourceAllocation',
  ],
  routes: [
    { path: '/project/list', component: () => import('./views/project-list'), title: 'All Projects', icon: 'folder' },
    { path: '/project/new', component: () => import('./views/project-form'), title: 'New Project', icon: 'plus' },
    { path: '/project/:id', component: () => import('./views/project-form'), title: 'Edit Project', icon: 'edit' },
    { path: '/project/:id/gantt', component: () => import('./views/gantt'), title: 'Gantt Chart', icon: 'bar-chart-2' },
    { path: '/project/:id/tasks', component: () => import('./views/tasks'), title: 'Tasks', icon: 'check-square' },
    { path: '/project/:id/daily-log', component: () => import('./views/daily-log'), title: 'Daily Log', icon: 'clipboard' },
    { path: '/project/:id/rfis', component: () => import('./views/rfis'), title: 'RFIs', icon: 'help-circle' },
    { path: '/project/:id/submittals', component: () => import('./views/submittals'), title: 'Submittals', icon: 'file-text' },
    { path: '/project/:id/meetings', component: () => import('./views/meetings'), title: 'Meetings', icon: 'users' },
    { path: '/project/:id/evm', component: () => import('./views/evm'), title: 'Earned Value', icon: 'trending-up' },
    { path: '/project/:id/look-ahead', component: () => import('./views/look-ahead'), title: 'Look-Ahead', icon: 'calendar' },
    { path: '/project/:id/weather-delays', component: () => import('./views/weather-delays'), title: 'Weather Delays', icon: 'cloud-rain' },
  ],
  navItems: [
    { id: 'project', label: 'Projects', icon: 'folder', path: '/project/list', order: 180 },
    { id: 'project-list', label: 'All Projects', icon: 'list', path: '/project/list', order: 1, parent: 'project' },
    { id: 'project-gantt', label: 'Gantt', icon: 'bar-chart-2', path: '/project/list', order: 2, parent: 'project' },
    { id: 'project-tasks', label: 'Tasks', icon: 'check-square', path: '/project/list', order: 3, parent: 'project' },
    { id: 'project-daily-log', label: 'Daily Log', icon: 'clipboard', path: '/project/list', order: 4, parent: 'project' },
    { id: 'project-rfis', label: 'RFIs', icon: 'help-circle', path: '/project/list', order: 5, parent: 'project' },
    { id: 'project-submittals', label: 'Submittals', icon: 'file-text', path: '/project/list', order: 6, parent: 'project' },
    { id: 'project-meetings', label: 'Meetings', icon: 'users', path: '/project/list', order: 7, parent: 'project' },
    { id: 'project-evm', label: 'EVM', icon: 'trending-up', path: '/project/list', order: 8, parent: 'project' },
  ],
  dashboardWidgets: [],
  settings: [],
  permissions: [
    { resource: 'project', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Project management' },
    { resource: 'project.task', actions: ['create', 'read', 'update', 'delete'], description: 'Task management' },
    { resource: 'project.milestone', actions: ['create', 'read', 'update', 'complete'], description: 'Milestone management' },
    { resource: 'project.rfi', actions: ['create', 'read', 'respond', 'close'], description: 'RFI management' },
    { resource: 'project.submittal', actions: ['create', 'read', 'review'], description: 'Submittal management' },
    { resource: 'project.dailyLog', actions: ['create', 'read', 'update'], description: 'Daily log management' },
    { resource: 'project.meetingMinutes', actions: ['create', 'read'], description: 'Meeting minutes' },
    { resource: 'project.weatherDelay', actions: ['create', 'read'], description: 'Weather delay logging' },
    { resource: 'project.resource', actions: ['allocate', 'read'], description: 'Resource allocation' },
    { resource: 'project.report', actions: ['read', 'export'], description: 'Project reports (EVM, schedule)' },
  ],
  workflows: [],
  importTypes: [
    {
      id: 'project-tasks',
      label: 'Import Project Tasks',
      collection: 'project/task',
      fields: [
        { name: 'name', type: 'string', required: true, label: 'Task Name' },
        { name: 'startDate', type: 'string', label: 'Start Date' },
        { name: 'endDate', type: 'string', label: 'End Date' },
        { name: 'duration', type: 'number', label: 'Duration (days)' },
        { name: 'assignee', type: 'string', label: 'Assignee' },
        { name: 'percentComplete', type: 'number', label: '% Complete' },
      ],
      autoDetectHeaders: true,
    },
  ],
  exportTypes: [
    { id: 'project-schedule', label: 'Export Project Schedule', collection: 'project/task', defaultFields: ['name', 'startDate', 'endDate', 'duration', 'percentComplete', 'status', 'assignee'] },
    { id: 'project-rfis', label: 'Export RFIs', collection: 'project/rfi', defaultFields: ['number', 'subject', 'status', 'priority', 'assignedTo', 'dueDate'] },
    { id: 'project-submittals', label: 'Export Submittals', collection: 'project/submittal', defaultFields: ['number', 'specSection', 'description', 'status', 'submittedDate', 'reviewedDate'] },
  ],
  hooks: [],
};
