import type { ModuleManifest } from '../../core/types/module';

export const apManifest: ModuleManifest = {
  id: 'concrete.ap',
  name: 'Accounts Payable',
  description: 'Vendor management, invoice processing, payments, retention, lien waivers, compliance, and 1099 reporting',
  version: '1.0.0',
  phase: 4,
  dependencies: ['concrete.gl', 'concrete.entity', 'concrete.job'],
  collections: [
    'ap/vendor', 'ap/invoice', 'ap/invoiceLine', 'ap/payment',
    'ap/paymentLine', 'ap/lienWaiver', 'ap/complianceCert', 'ap/retention',
  ],
  routes: [
    { path: '/ap/vendors', component: () => import('./views/vendor-list'), title: 'Vendors', icon: 'users' },
    { path: '/ap/vendors/new', component: () => import('./views/vendor-form'), title: 'New Vendor', icon: 'user-plus' },
    { path: '/ap/vendors/:id', component: () => import('./views/vendor-form'), title: 'Edit Vendor', icon: 'edit' },
    { path: '/ap/invoices', component: () => import('./views/invoice-list'), title: 'Invoices', icon: 'file-text' },
    { path: '/ap/invoices/new', component: () => import('./views/invoice-form'), title: 'New Invoice', icon: 'plus' },
    { path: '/ap/invoices/:id', component: () => import('./views/invoice-form'), title: 'Edit Invoice', icon: 'edit' },
    { path: '/ap/payments', component: () => import('./views/payments'), title: 'Payments', icon: 'credit-card' },
    { path: '/ap/aging', component: () => import('./views/aging'), title: 'Aging Report', icon: 'clock' },
    { path: '/ap/1099', component: () => import('./views/report-1099'), title: '1099 Report', icon: 'file' },
    { path: '/ap/lien-waivers', component: () => import('./views/lien-waivers'), title: 'Lien Waivers', icon: 'shield' },
    { path: '/ap/compliance', component: () => import('./views/compliance'), title: 'Compliance', icon: 'check-circle' },
    { path: '/ap/retention', component: () => import('./views/retention'), title: 'Retention', icon: 'lock' },
  ],
  navItems: [
    { id: 'ap', label: 'AP', icon: 'credit-card', path: '/ap/vendors', order: 40 },
    { id: 'ap-vendors', label: 'Vendors', icon: 'users', path: '/ap/vendors', order: 1, parent: 'ap' },
    { id: 'ap-invoices', label: 'Invoices', icon: 'file-text', path: '/ap/invoices', order: 2, parent: 'ap' },
    { id: 'ap-payments', label: 'Payments', icon: 'credit-card', path: '/ap/payments', order: 3, parent: 'ap' },
    { id: 'ap-aging', label: 'Aging', icon: 'clock', path: '/ap/aging', order: 4, parent: 'ap' },
    { id: 'ap-1099', label: '1099', icon: 'file', path: '/ap/1099', order: 5, parent: 'ap' },
    { id: 'ap-lien-waivers', label: 'Lien Waivers', icon: 'shield', path: '/ap/lien-waivers', order: 6, parent: 'ap' },
    { id: 'ap-compliance', label: 'Compliance', icon: 'check-circle', path: '/ap/compliance', order: 7, parent: 'ap' },
    { id: 'ap-retention', label: 'Retention', icon: 'lock', path: '/ap/retention', order: 8, parent: 'ap' },
  ],
  dashboardWidgets: [],
  settings: [],
  permissions: [
    { resource: 'vendor', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Vendor management' },
    { resource: 'ap.invoice', actions: ['create', 'read', 'update', 'approve', 'void', 'export'], description: 'AP invoice management' },
    { resource: 'ap.payment', actions: ['create', 'read', 'void', 'export'], description: 'Payment processing' },
    { resource: 'ap.retention', actions: ['create', 'read', 'release', 'export'], description: 'Retention tracking' },
    { resource: 'ap.lienWaiver', actions: ['create', 'read', 'update', 'export'], description: 'Lien waiver tracking' },
    { resource: 'ap.compliance', actions: ['create', 'read', 'update', 'export'], description: 'Compliance certificate tracking' },
    { resource: 'ap.report', actions: ['read', 'export'], description: 'AP reports (aging, 1099)' },
  ],
  workflows: [],
  importTypes: [
    {
      id: 'ap-invoices',
      label: 'Import AP Invoices',
      collection: 'ap/invoice',
      fields: [
        { name: 'vendorName', type: 'string', required: true, label: 'Vendor Name' },
        { name: 'invoiceNumber', type: 'string', required: true, label: 'Invoice Number' },
        { name: 'invoiceDate', type: 'string', required: true, label: 'Invoice Date' },
        { name: 'amount', type: 'number', required: true, label: 'Amount' },
        { name: 'dueDate', type: 'string', label: 'Due Date' },
        { name: 'description', type: 'string', label: 'Description' },
      ],
      autoDetectHeaders: true,
    },
  ],
  exportTypes: [
    { id: 'ap-aging', label: 'Export AP Aging', collection: 'ap/invoice', defaultFields: ['vendorId', 'invoiceNumber', 'invoiceDate', 'dueDate', 'amount', 'balanceDue', 'status'] },
    { id: 'ap-1099', label: 'Export 1099 Data', collection: 'ap/vendor', defaultFields: ['name', 'taxId', 'form1099Type', 'ytd1099Amount', 'address', 'city', 'state', 'zip'] },
  ],
  hooks: [],
};
