import type { ModuleManifest } from '../../core/types/module';

export const reportsManifest: ModuleManifest = {
  id: 'concrete.reports',
  name: 'Financial Reporting Suite',
  description: 'Comprehensive financial reports: balance sheet, income statement, cash flow, WIP schedule, job cost, aging, payroll, equipment, bonding capacity, and custom report builder with templates',
  version: '1.0.0',
  phase: 11,
  dependencies: ['concrete.gl', 'concrete.entity', 'concrete.job', 'concrete.ap', 'concrete.ar', 'concrete.payroll'],
  collections: [
    'reports/template',
  ],
  routes: [
    { path: '/reports', component: () => import('./views/report-list'), title: 'Reports', icon: 'bar-chart-2' },
    { path: '/reports/balance-sheet', component: () => import('./views/balance-sheet'), title: 'Balance Sheet', icon: 'columns' },
    { path: '/reports/income-statement', component: () => import('./views/income-statement'), title: 'Income Statement', icon: 'trending-up' },
    { path: '/reports/cash-flow', component: () => import('./views/cash-flow'), title: 'Cash Flow Statement', icon: 'activity' },
    { path: '/reports/wip', component: () => import('./views/wip-report'), title: 'WIP Schedule', icon: 'clipboard' },
    { path: '/reports/job-cost', component: () => import('./views/job-cost'), title: 'Job Cost Reports', icon: 'hard-hat' },
    { path: '/reports/aging', component: () => import('./views/aging-report'), title: 'Aging Reports', icon: 'clock' },
    { path: '/reports/payroll', component: () => import('./views/payroll-report'), title: 'Payroll Reports', icon: 'users' },
    { path: '/reports/equipment', component: () => import('./views/equipment-report'), title: 'Equipment Reports', icon: 'truck' },
    { path: '/reports/bonding', component: () => import('./views/bonding-capacity'), title: 'Bonding Capacity', icon: 'shield' },
    { path: '/reports/templates', component: () => import('./views/templates'), title: 'Report Templates', icon: 'file-text' },
    { path: '/reports/custom', component: () => import('./views/custom-builder'), title: 'Custom Report Builder', icon: 'sliders' },
  ],
  navItems: [
    { id: 'reports', label: 'Reports', icon: 'bar-chart-2', path: '/reports', order: 110 },
    { id: 'reports-balance-sheet', label: 'Balance Sheet', icon: 'columns', path: '/reports/balance-sheet', order: 1, parent: 'reports' },
    { id: 'reports-income-statement', label: 'Income Statement', icon: 'trending-up', path: '/reports/income-statement', order: 2, parent: 'reports' },
    { id: 'reports-cash-flow', label: 'Cash Flow', icon: 'activity', path: '/reports/cash-flow', order: 3, parent: 'reports' },
    { id: 'reports-wip', label: 'WIP Schedule', icon: 'clipboard', path: '/reports/wip', order: 4, parent: 'reports' },
    { id: 'reports-job-cost', label: 'Job Cost', icon: 'hard-hat', path: '/reports/job-cost', order: 5, parent: 'reports' },
    { id: 'reports-aging', label: 'Aging', icon: 'clock', path: '/reports/aging', order: 6, parent: 'reports' },
    { id: 'reports-payroll', label: 'Payroll', icon: 'users', path: '/reports/payroll', order: 7, parent: 'reports' },
    { id: 'reports-equipment', label: 'Equipment', icon: 'truck', path: '/reports/equipment', order: 8, parent: 'reports' },
    { id: 'reports-bonding', label: 'Bonding Capacity', icon: 'shield', path: '/reports/bonding', order: 9, parent: 'reports' },
    { id: 'reports-templates', label: 'Templates', icon: 'file-text', path: '/reports/templates', order: 10, parent: 'reports' },
    { id: 'reports-custom', label: 'Custom Builder', icon: 'sliders', path: '/reports/custom', order: 11, parent: 'reports' },
  ],
  dashboardWidgets: [],
  settings: [],
  permissions: [
    { resource: 'reports.balanceSheet', actions: ['read', 'export'], description: 'Balance sheet report generation and export' },
    { resource: 'reports.incomeStatement', actions: ['read', 'export'], description: 'Income statement report generation and export' },
    { resource: 'reports.cashFlow', actions: ['read', 'export'], description: 'Cash flow statement generation and export' },
    { resource: 'reports.wip', actions: ['read', 'export'], description: 'WIP schedule generation and export' },
    { resource: 'reports.jobCost', actions: ['read', 'export'], description: 'Job cost report generation and export' },
    { resource: 'reports.aging', actions: ['read', 'export'], description: 'Aging report generation and export' },
    { resource: 'reports.payroll', actions: ['read', 'export'], description: 'Payroll report generation and export' },
    { resource: 'reports.equipment', actions: ['read', 'export'], description: 'Equipment report generation and export' },
    { resource: 'reports.bonding', actions: ['read', 'export'], description: 'Bonding capacity analysis and export' },
    { resource: 'reports.template', actions: ['create', 'read', 'update', 'delete'], description: 'Report template management' },
    { resource: 'reports.custom', actions: ['create', 'read', 'export'], description: 'Custom report builder' },
  ],
  workflows: [],
  importTypes: [],
  exportTypes: [
    { id: 'reports-balance-sheet', label: 'Export Balance Sheet', collection: 'reports/template', defaultFields: ['accountNumber', 'accountName', 'accountType', 'currentBalance', 'priorBalance', 'change'] },
    { id: 'reports-income-statement', label: 'Export Income Statement', collection: 'reports/template', defaultFields: ['accountNumber', 'accountName', 'category', 'currentAmount', 'priorAmount', 'variance'] },
    { id: 'reports-cash-flow', label: 'Export Cash Flow Statement', collection: 'reports/template', defaultFields: ['category', 'description', 'amount'] },
    { id: 'reports-wip-schedule', label: 'Export WIP Schedule', collection: 'reports/template', defaultFields: ['jobNumber', 'jobName', 'contractAmount', 'actualCostToDate', 'percentComplete', 'earnedRevenue', 'overUnderBilling'] },
    { id: 'reports-job-cost', label: 'Export Job Cost Summary', collection: 'reports/template', defaultFields: ['jobNumber', 'jobName', 'contractAmount', 'actualCostToDate', 'projectedCost', 'projectedProfit', 'projectedMarginPct'] },
    { id: 'reports-aging', label: 'Export Aging Report', collection: 'reports/template', defaultFields: ['entityName', 'current', 'days30', 'days60', 'days90', 'days120Plus', 'total'] },
    { id: 'reports-payroll', label: 'Export Payroll Summary', collection: 'reports/template', defaultFields: ['employeeName', 'department', 'totalGross', 'totalNet', 'totalHours'] },
  ],
  hooks: [],
};
