export const intercompanyManifest = {
  id: 'concrete.intercompany', name: 'Intercompany & Consolidated Accounting', description: 'Multi-entity financial management with IC transactions, eliminations, transfer pricing, allocations, and consolidated reporting.', version: '1.0.0', phase: 29, dependencies: ['concrete.gl'],
  collections: ['ic/transaction','ic/elimination','ic/transferPricing','ic/allocation','ic/managementFee','ic/trialBalance','ic/statement','ic/translation','ic/reconciliation','ic/segment'],
  routes: [
    { path: '/intercompany/transactions', component: () => import('./views/transactions'), title: 'IC Transactions', icon: 'repeat' },
    { path: '/intercompany/eliminations', component: () => import('./views/eliminations'), title: 'Eliminations', icon: 'minus-circle' },
    { path: '/intercompany/transfer-pricing', component: () => import('./views/transfer-pricing'), title: 'Transfer Pricing', icon: 'tag' },
    { path: '/intercompany/allocations', component: () => import('./views/allocations'), title: 'Allocations', icon: 'pie-chart' },
    { path: '/intercompany/mgmt-fees', component: () => import('./views/mgmt-fees'), title: 'Management Fees', icon: 'dollar-sign' },
    { path: '/intercompany/trial-balance', component: () => import('./views/trial-balance'), title: 'Trial Balance', icon: 'book' },
    { path: '/intercompany/statements', component: () => import('./views/statements'), title: 'Statements', icon: 'file-text' },
    { path: '/intercompany/currency', component: () => import('./views/currency'), title: 'Currency', icon: 'globe' },
    { path: '/intercompany/reconciliation', component: () => import('./views/reconciliation'), title: 'Reconciliation', icon: 'check-circle' },
    { path: '/intercompany/segments', component: () => import('./views/segments'), title: 'Segments', icon: 'layers' },
  ],
  navItems: [
    { id: 'intercompany', label: 'Intercompany', icon: 'repeat', path: '/intercompany/transactions', order: 290 },
    { id: 'ic-txns', label: 'Transactions', icon: 'repeat', path: '/intercompany/transactions', order: 1, parent: 'intercompany' },
    { id: 'ic-elim', label: 'Eliminations', icon: 'minus-circle', path: '/intercompany/eliminations', order: 2, parent: 'intercompany' },
    { id: 'ic-tp', label: 'Transfer Pricing', icon: 'tag', path: '/intercompany/transfer-pricing', order: 3, parent: 'intercompany' },
    { id: 'ic-alloc', label: 'Allocations', icon: 'pie-chart', path: '/intercompany/allocations', order: 4, parent: 'intercompany' },
    { id: 'ic-fees', label: 'Mgmt Fees', icon: 'dollar-sign', path: '/intercompany/mgmt-fees', order: 5, parent: 'intercompany' },
    { id: 'ic-tb', label: 'Trial Balance', icon: 'book', path: '/intercompany/trial-balance', order: 6, parent: 'intercompany' },
    { id: 'ic-stmts', label: 'Statements', icon: 'file-text', path: '/intercompany/statements', order: 7, parent: 'intercompany' },
    { id: 'ic-curr', label: 'Currency', icon: 'globe', path: '/intercompany/currency', order: 8, parent: 'intercompany' },
    { id: 'ic-recon', label: 'Reconciliation', icon: 'check-circle', path: '/intercompany/reconciliation', order: 9, parent: 'intercompany' },
    { id: 'ic-seg', label: 'Segments', icon: 'layers', path: '/intercompany/segments', order: 10, parent: 'intercompany' },
  ],
  dashboardWidgets: [], settings: [], permissions: [
    { resource: 'ic.transaction', actions: ['create','read','post','eliminate'], description: 'IC transactions' },
    { resource: 'ic.elimination', actions: ['create','read','approve','post'], description: 'Elimination entries' },
    { resource: 'ic.allocation', actions: ['create','read','post'], description: 'Shared service allocations' },
    { resource: 'ic.report', actions: ['read','export'], description: 'Consolidated reporting' },
  ], workflows: [], importTypes: [], exportTypes: [], hooks: [],
};
