import type { ModuleManifest } from '../../core/types/module';

export const unionManifest: ModuleManifest = {
  id: 'concrete.union',
  name: 'Union & Prevailing Wage',
  description: 'Union master file, pay scale tables, fringe benefits, prevailing wage tracking, Davis-Bacon compliance, certified payroll (WH-347), apprentice ratio tracking, and remittance reporting',
  version: '1.0.0',
  phase: 7,
  dependencies: ['concrete.gl', 'concrete.entity', 'concrete.job', 'concrete.payroll'],
  collections: [
    'union/union', 'union/rateTable', 'union/rateTableLine', 'union/fringeBenefit',
    'union/prevailingWage', 'union/certifiedPayroll', 'union/apprentice', 'union/remittance',
  ],
  routes: [
    { path: '/union/unions', component: () => import('./views/union-list'), title: 'Unions', icon: 'hard-hat' },
    { path: '/union/unions/new', component: () => import('./views/union-form'), title: 'New Union', icon: 'plus' },
    { path: '/union/unions/:id', component: () => import('./views/union-form'), title: 'Edit Union', icon: 'edit' },
    { path: '/union/rate-tables', component: () => import('./views/rate-tables'), title: 'Rate Tables', icon: 'table' },
    { path: '/union/prevailing-wage', component: () => import('./views/prevailing-wage'), title: 'Prevailing Wage', icon: 'scale' },
    { path: '/union/certified-payroll', component: () => import('./views/certified-payroll'), title: 'Certified Payroll', icon: 'file-check' },
    { path: '/union/apprentices', component: () => import('./views/apprentices'), title: 'Apprentices', icon: 'graduation-cap' },
    { path: '/union/remittances', component: () => import('./views/remittances'), title: 'Remittances', icon: 'send' },
    { path: '/union/fringes', component: () => import('./views/fringes'), title: 'Fringe Benefits', icon: 'heart' },
    { path: '/union/rate-lookup', component: () => import('./views/rate-lookup'), title: 'Rate Lookup', icon: 'search' },
  ],
  navItems: [
    { id: 'union', label: 'Union', icon: 'hard-hat', path: '/union/unions', order: 70 },
    { id: 'union-list', label: 'Unions', icon: 'hard-hat', path: '/union/unions', order: 1, parent: 'union' },
    { id: 'union-rate-tables', label: 'Rate Tables', icon: 'table', path: '/union/rate-tables', order: 2, parent: 'union' },
    { id: 'union-prevailing-wage', label: 'Prevailing Wage', icon: 'scale', path: '/union/prevailing-wage', order: 3, parent: 'union' },
    { id: 'union-certified-payroll', label: 'Certified Payroll', icon: 'file-check', path: '/union/certified-payroll', order: 4, parent: 'union' },
    { id: 'union-apprentices', label: 'Apprentices', icon: 'graduation-cap', path: '/union/apprentices', order: 5, parent: 'union' },
    { id: 'union-remittances', label: 'Remittances', icon: 'send', path: '/union/remittances', order: 6, parent: 'union' },
    { id: 'union-fringes', label: 'Fringe Benefits', icon: 'heart', path: '/union/fringes', order: 7, parent: 'union' },
    { id: 'union-rate-lookup', label: 'Rate Lookup', icon: 'search', path: '/union/rate-lookup', order: 8, parent: 'union' },
  ],
  dashboardWidgets: [],
  settings: [],
  permissions: [
    { resource: 'union.union', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Union master file management' },
    { resource: 'union.rateTable', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Union rate table management' },
    { resource: 'union.fringeBenefit', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Fringe benefit configuration' },
    { resource: 'union.prevailingWage', actions: ['create', 'read', 'update', 'delete', 'export', 'import'], description: 'Prevailing wage table management' },
    { resource: 'union.certifiedPayroll', actions: ['create', 'read', 'update', 'submit', 'approve', 'export'], description: 'Certified payroll report management' },
    { resource: 'union.apprentice', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Apprentice tracking' },
    { resource: 'union.remittance', actions: ['create', 'read', 'update', 'submit', 'pay', 'export'], description: 'Remittance report management' },
    { resource: 'union.report', actions: ['read', 'export'], description: 'Union reports (rate lookup, compliance)' },
  ],
  workflows: [],
  importTypes: [
    {
      id: 'union-rate-tables',
      label: 'Import Union Rate Tables',
      collection: 'union/rateTableLine',
      fields: [
        { name: 'unionLocalNumber', type: 'string', required: true, label: 'Union Local Number' },
        { name: 'rateTableName', type: 'string', required: true, label: 'Rate Table Name' },
        { name: 'classification', type: 'string', required: true, label: 'Classification' },
        { name: 'category', type: 'string', required: true, label: 'Category' },
        { name: 'description', type: 'string', label: 'Description' },
        { name: 'rate', type: 'number', required: true, label: 'Rate' },
        { name: 'method', type: 'string', required: true, label: 'Method (hourly/percent/flat)' },
        { name: 'payableTo', type: 'string', required: true, label: 'Payable To (employee/fund)' },
        { name: 'fundName', type: 'string', label: 'Fund Name' },
        { name: 'effectiveDate', type: 'string', required: true, label: 'Effective Date' },
        { name: 'expirationDate', type: 'string', label: 'Expiration Date' },
      ],
      autoDetectHeaders: true,
    },
    {
      id: 'union-prevailing-wage',
      label: 'Import Prevailing Wage Schedules',
      collection: 'union/prevailingWage',
      fields: [
        { name: 'jurisdiction', type: 'string', required: true, label: 'Jurisdiction' },
        { name: 'state', type: 'string', required: true, label: 'State' },
        { name: 'county', type: 'string', label: 'County' },
        { name: 'projectType', type: 'string', required: true, label: 'Project Type (federal/state/local)' },
        { name: 'classification', type: 'string', required: true, label: 'Classification' },
        { name: 'trade', type: 'string', required: true, label: 'Trade' },
        { name: 'baseRate', type: 'number', required: true, label: 'Base Rate' },
        { name: 'fringeRate', type: 'number', required: true, label: 'Fringe Rate' },
        { name: 'effectiveDate', type: 'string', required: true, label: 'Effective Date' },
        { name: 'expirationDate', type: 'string', label: 'Expiration Date' },
        { name: 'source', type: 'string', required: true, label: 'Source (davis_bacon/state/local)' },
      ],
      autoDetectHeaders: true,
    },
  ],
  exportTypes: [
    { id: 'union-list', label: 'Export Unions', collection: 'union/union', defaultFields: ['name', 'localNumber', 'trade', 'jurisdiction', 'status', 'contactName', 'contactPhone', 'contactEmail'] },
    { id: 'union-rate-tables', label: 'Export Rate Tables', collection: 'union/rateTable', defaultFields: ['unionId', 'name', 'classification', 'effectiveDate', 'expirationDate', 'journeymanRate', 'status'] },
    { id: 'union-prevailing-wage', label: 'Export Prevailing Wage', collection: 'union/prevailingWage', defaultFields: ['jurisdiction', 'state', 'county', 'projectType', 'classification', 'trade', 'baseRate', 'fringeRate', 'totalRate', 'effectiveDate', 'source'] },
    { id: 'union-certified-payroll', label: 'Export Certified Payroll', collection: 'union/certifiedPayroll', defaultFields: ['jobId', 'weekEndingDate', 'contractorName', 'projectName', 'totalGross', 'totalFringe', 'totalNet', 'status'] },
    { id: 'union-remittances', label: 'Export Remittances', collection: 'union/remittance', defaultFields: ['unionId', 'periodStart', 'periodEnd', 'totalHours', 'totalAmount', 'employeeCount', 'status'] },
  ],
  hooks: [],
};
