import type { ModuleManifest } from '../../core/types/module';

export const equipManifest: ModuleManifest = {
  id: 'concrete.equip',
  name: 'Equipment Management',
  description: 'Equipment master, rate tables, usage tracking, fuel logs, maintenance scheduling, work orders, depreciation, utilization analysis, and P&L reporting',
  version: '1.0.0',
  phase: 8,
  dependencies: ['concrete.gl', 'concrete.entity', 'concrete.job'],
  collections: [
    'equip/equipment', 'equip/rateTable', 'equip/usage', 'equip/maintenance',
    'equip/workOrder', 'equip/fuelLog', 'equip/depreciation',
  ],
  routes: [
    { path: '/equipment', component: () => import('./views/equipment-list'), title: 'Equipment', icon: 'truck' },
    { path: '/equipment/new', component: () => import('./views/equipment-form'), title: 'New Equipment', icon: 'plus' },
    { path: '/equipment/:id', component: () => import('./views/equipment-form'), title: 'Edit Equipment', icon: 'edit' },
    { path: '/equipment/usage', component: () => import('./views/usage'), title: 'Usage Log', icon: 'clock' },
    { path: '/equipment/maintenance', component: () => import('./views/maintenance'), title: 'Maintenance', icon: 'tool' },
    { path: '/equipment/fuel-logs', component: () => import('./views/fuel-logs'), title: 'Fuel Logs', icon: 'droplet' },
    { path: '/equipment/utilization', component: () => import('./views/utilization'), title: 'Utilization', icon: 'bar-chart-2' },
    { path: '/equipment/depreciation', component: () => import('./views/depreciation'), title: 'Depreciation', icon: 'trending-down' },
    { path: '/equipment/work-orders', component: () => import('./views/work-orders'), title: 'Work Orders', icon: 'clipboard' },
  ],
  navItems: [
    { id: 'equip', label: 'Equipment', icon: 'truck', path: '/equipment', order: 80 },
    { id: 'equip-list', label: 'Equipment List', icon: 'truck', path: '/equipment', order: 1, parent: 'equip' },
    { id: 'equip-usage', label: 'Usage Log', icon: 'clock', path: '/equipment/usage', order: 2, parent: 'equip' },
    { id: 'equip-maintenance', label: 'Maintenance', icon: 'tool', path: '/equipment/maintenance', order: 3, parent: 'equip' },
    { id: 'equip-fuel', label: 'Fuel Logs', icon: 'droplet', path: '/equipment/fuel-logs', order: 4, parent: 'equip' },
    { id: 'equip-utilization', label: 'Utilization', icon: 'bar-chart-2', path: '/equipment/utilization', order: 5, parent: 'equip' },
    { id: 'equip-depreciation', label: 'Depreciation', icon: 'trending-down', path: '/equipment/depreciation', order: 6, parent: 'equip' },
    { id: 'equip-work-orders', label: 'Work Orders', icon: 'clipboard', path: '/equipment/work-orders', order: 7, parent: 'equip' },
  ],
  dashboardWidgets: [],
  settings: [],
  permissions: [
    { resource: 'equip.equipment', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Equipment master management' },
    { resource: 'equip.rateTable', actions: ['create', 'read', 'update', 'delete'], description: 'Rate table management' },
    { resource: 'equip.usage', actions: ['create', 'read', 'update', 'post', 'export'], description: 'Usage logging and posting' },
    { resource: 'equip.maintenance', actions: ['create', 'read', 'update', 'complete'], description: 'Maintenance scheduling' },
    { resource: 'equip.workOrder', actions: ['create', 'read', 'update', 'complete', 'cancel'], description: 'Work order management' },
    { resource: 'equip.fuelLog', actions: ['create', 'read', 'update', 'export'], description: 'Fuel log tracking' },
    { resource: 'equip.depreciation', actions: ['create', 'read', 'export'], description: 'Depreciation calculation' },
    { resource: 'equip.report', actions: ['read', 'export'], description: 'Equipment reports (utilization, P&L, FHWA)' },
  ],
  workflows: [],
  importTypes: [
    {
      id: 'equip-equipment',
      label: 'Import Equipment List',
      collection: 'equip/equipment',
      fields: [
        { name: 'equipmentNumber', type: 'string', required: true, label: 'Equipment Number' },
        { name: 'description', type: 'string', required: true, label: 'Description' },
        { name: 'year', type: 'number', label: 'Year' },
        { name: 'make', type: 'string', label: 'Make' },
        { name: 'model', type: 'string', label: 'Model' },
        { name: 'serialNumber', type: 'string', label: 'Serial Number' },
        { name: 'vin', type: 'string', label: 'VIN' },
        { name: 'licensePlate', type: 'string', label: 'License Plate' },
        { name: 'category', type: 'string', required: true, label: 'Category (owned/leased/rented/idle)' },
        { name: 'purchaseDate', type: 'string', label: 'Purchase Date' },
        { name: 'purchasePrice', type: 'number', label: 'Purchase Price' },
        { name: 'salvageValue', type: 'number', label: 'Salvage Value' },
        { name: 'usefulLifeMonths', type: 'number', label: 'Useful Life (Months)' },
        { name: 'depreciationMethod', type: 'string', label: 'Depreciation Method' },
      ],
      autoDetectHeaders: true,
    },
  ],
  exportTypes: [
    {
      id: 'equip-utilization',
      label: 'Export Equipment Utilization',
      collection: 'equip/usage',
      defaultFields: ['equipmentId', 'jobId', 'date', 'hours', 'days', 'rate', 'amount', 'posted'],
    },
    {
      id: 'equip-list',
      label: 'Export Equipment List',
      collection: 'equip/equipment',
      defaultFields: ['equipmentNumber', 'description', 'year', 'make', 'model', 'serialNumber', 'category', 'status', 'purchasePrice', 'currentValue'],
    },
  ],
  hooks: [],
};
