import type { ModuleManifest } from '../../core/types/module';

export const subManifest: ModuleManifest = {
  id: 'concrete.sub',
  name: 'Subcontractor Management',
  description: 'Subcontract creation, change orders, payment applications, backcharges, prequalification, compliance matrix, retention tracking, and performance scoring',
  version: '1.0.0',
  phase: 9,
  dependencies: ['concrete.gl', 'concrete.entity', 'concrete.job', 'concrete.ap'],
  collections: [
    'sub/subcontract', 'sub/changeOrder', 'sub/payApp',
    'sub/backcharge', 'sub/prequalification', 'sub/compliance',
  ],
  routes: [
    { path: '/sub/contracts', component: () => import('./views/subcontract-list'), title: 'Subcontracts', icon: 'file-text' },
    { path: '/sub/contracts/new', component: () => import('./views/subcontract-form'), title: 'New Subcontract', icon: 'plus' },
    { path: '/sub/contracts/:id', component: () => import('./views/subcontract-form'), title: 'Edit Subcontract', icon: 'edit' },
    { path: '/sub/contracts/:id/sov', component: () => import('./views/sov'), title: 'Schedule of Values', icon: 'list' },
    { path: '/sub/change-orders', component: () => import('./views/change-orders'), title: 'Change Orders', icon: 'git-branch' },
    { path: '/sub/pay-apps', component: () => import('./views/pay-apps'), title: 'Pay Applications', icon: 'dollar-sign' },
    { path: '/sub/backcharges', component: () => import('./views/backcharges'), title: 'Backcharges', icon: 'alert-circle' },
    { path: '/sub/prequalification', component: () => import('./views/prequalification'), title: 'Prequalification', icon: 'clipboard' },
    { path: '/sub/compliance', component: () => import('./views/compliance'), title: 'Compliance Matrix', icon: 'check-circle' },
    { path: '/sub/payment-history', component: () => import('./views/payment-history'), title: 'Payment History', icon: 'credit-card' },
  ],
  navItems: [
    { id: 'sub', label: 'Subs', icon: 'hard-hat', path: '/sub/contracts', order: 90 },
    { id: 'sub-contracts', label: 'Subcontracts', icon: 'file-text', path: '/sub/contracts', order: 1, parent: 'sub' },
    { id: 'sub-change-orders', label: 'Change Orders', icon: 'git-branch', path: '/sub/change-orders', order: 2, parent: 'sub' },
    { id: 'sub-pay-apps', label: 'Pay Apps', icon: 'dollar-sign', path: '/sub/pay-apps', order: 3, parent: 'sub' },
    { id: 'sub-backcharges', label: 'Backcharges', icon: 'alert-circle', path: '/sub/backcharges', order: 4, parent: 'sub' },
    { id: 'sub-prequalification', label: 'Prequalification', icon: 'clipboard', path: '/sub/prequalification', order: 5, parent: 'sub' },
    { id: 'sub-compliance', label: 'Compliance', icon: 'check-circle', path: '/sub/compliance', order: 6, parent: 'sub' },
    { id: 'sub-payment-history', label: 'Payment History', icon: 'credit-card', path: '/sub/payment-history', order: 7, parent: 'sub' },
  ],
  dashboardWidgets: [],
  settings: [],
  permissions: [
    { resource: 'sub.subcontract', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Subcontract management' },
    { resource: 'sub.changeOrder', actions: ['create', 'read', 'update', 'approve', 'reject', 'export'], description: 'Change order management' },
    { resource: 'sub.payApp', actions: ['create', 'read', 'update', 'submit', 'approve', 'pay', 'export'], description: 'Payment application processing' },
    { resource: 'sub.backcharge', actions: ['create', 'read', 'approve', 'deduct', 'export'], description: 'Backcharge tracking' },
    { resource: 'sub.prequalification', actions: ['create', 'read', 'update', 'approve', 'reject', 'export'], description: 'Prequalification tracking' },
    { resource: 'sub.compliance', actions: ['create', 'read', 'update', 'export'], description: 'Compliance matrix management' },
    { resource: 'sub.report', actions: ['read', 'export'], description: 'Subcontractor reports (payment history, compliance matrix, open commitments)' },
  ],
  workflows: [],
  importTypes: [
    {
      id: 'sub-subcontracts',
      label: 'Import Subcontracts',
      collection: 'sub/subcontract',
      fields: [
        { name: 'vendorName', type: 'string', required: true, label: 'Subcontractor Name' },
        { name: 'jobNumber', type: 'string', required: true, label: 'Job Number' },
        { name: 'number', type: 'string', required: true, label: 'Subcontract Number' },
        { name: 'description', type: 'string', label: 'Description' },
        { name: 'scope', type: 'string', label: 'Scope of Work' },
        { name: 'contractAmount', type: 'number', required: true, label: 'Contract Amount' },
        { name: 'retentionPct', type: 'number', label: 'Retention %' },
        { name: 'startDate', type: 'string', label: 'Start Date' },
        { name: 'endDate', type: 'string', label: 'End Date' },
        { name: 'status', type: 'string', label: 'Status' },
      ],
      autoDetectHeaders: true,
    },
  ],
  exportTypes: [
    {
      id: 'sub-payment-history',
      label: 'Export Sub Payment History',
      collection: 'sub/payApp',
      defaultFields: [
        'subcontractId', 'applicationNumber', 'periodTo',
        'previouslyBilled', 'currentBilled', 'materialStored',
        'totalBilled', 'retainageAmount', 'netPayable', 'status',
      ],
    },
    {
      id: 'sub-open-commitments',
      label: 'Export Open Commitments',
      collection: 'sub/subcontract',
      defaultFields: [
        'number', 'vendorId', 'jobId', 'contractAmount',
        'approvedChangeOrders', 'revisedAmount', 'billedToDate',
        'paidToDate', 'retainageHeld', 'status',
      ],
    },
  ],
  hooks: [],
};
