/**
 * UI layer barrel export — re-exports from components and theme.
 */

export {
  // Layout
  AppShell,
  TopNav,
  type NavItemConfig,
  Sidebar,
  type SidebarItem,
  ContentArea,
  SplitPane,
  type SplitPaneOptions,
  Grid,
  Stack,

  // Data Display
  DataTable,
  type DataTableColumn,
  type DataTableConfig,
  KPICard,
  type KPICardConfig,
  ConcreteChart,
  type ChartDataset,
  type ChartConfig,
  TreeView,
  type TreeNode,
  Timeline,
  type TimelineItem,
  Badge,
  HealthDot,
  ProgressBar,
  type ProgressBarThresholds,
  BreakdownBar,
  type BreakdownSegment,
  EmptyState,
  type EmptyStateConfig,
  Stat,
  type StatConfig,
  Avatar,
  type AvatarConfig,
  Tooltip,
  type TooltipConfig,

  // Forms
  Form,
  type FormConfig,
  TextField,
  type TextFieldConfig,
  NumberField,
  type NumberFieldConfig,
  CurrencyField,
  type CurrencyFieldConfig,
  DateField,
  type DateFieldConfig,
  SelectField,
  type SelectOption,
  type SelectFieldConfig,
  CheckboxField,
  type CheckboxFieldConfig,
  TextareaField,
  type TextareaFieldConfig,
  FileUpload,
  type FileUploadConfig,
  FormSection,
  type FormSectionConfig,
  FormActions,
  type FormActionsConfig,
  InlineEdit,
  type InlineEditConfig,

  // Overlays
  Modal,
  type ModalConfig,
  SlidePanel,
  type SlidePanelConfig,
  Drawer,
  type DrawerConfig,
  ConfirmDialog,
  type ConfirmDialogConfig,
  Toast,
  type ToastConfig,
  CommandPalette,
  type CommandItem,
  type CommandPaletteConfig,

  // Navigation
  Breadcrumb,
  type BreadcrumbItem,
  FilterBar,
  type FilterDefinition,
  type FilterBarConfig,
  Pagination,
  type PaginationConfig,
  TabNav,
  type TabItem,
  type TabNavConfig,
} from './components';

export {
  COLORS,
  FONT,
  SPACING,
  BREAKPOINTS,
  RADII,
  SHADOWS,
} from './theme';
