export const integrationManifest = {
  id: 'concrete.integration', name: 'Integration Hub', description: 'REST API, webhooks, third-party integrations (Procore, QuickBooks, ADP, Plaid, etc.), email forwarding, calendar sync, and SFTP flat file imports.', version: '1.0.0', phase: 31, dependencies: [],
  collections: ['integ/endpoint','integ/apiKey','integ/webhookConfig','integ/webhookLog','integ/integration','integ/mapping','integ/syncLog','integ/email','integ/calendarEvent','integ/flatFileConfig','integ/flatFileLog'],
  routes: [
    { path: '/integration/api-endpoints', component: () => import('./views/api-endpoints'), title: 'API Endpoints', icon: 'code' },
    { path: '/integration/api-keys', component: () => import('./views/api-keys'), title: 'API Keys', icon: 'key' },
    { path: '/integration/webhooks', component: () => import('./views/webhooks'), title: 'Webhooks', icon: 'send' },
    { path: '/integration/webhook-logs', component: () => import('./views/webhook-logs'), title: 'Webhook Logs', icon: 'file-text' },
    { path: '/integration/connections', component: () => import('./views/connections'), title: 'Connections', icon: 'link' },
    { path: '/integration/mappings', component: () => import('./views/mappings'), title: 'Field Mappings', icon: 'map' },
    { path: '/integration/sync-logs', component: () => import('./views/sync-logs'), title: 'Sync Logs', icon: 'refresh-cw' },
    { path: '/integration/email', component: () => import('./views/email'), title: 'Email Integration', icon: 'mail' },
    { path: '/integration/calendar', component: () => import('./views/calendar'), title: 'Calendar', icon: 'calendar' },
    { path: '/integration/sftp', component: () => import('./views/sftp'), title: 'SFTP / Flat File', icon: 'upload' },
    { path: '/integration/sftp-logs', component: () => import('./views/sftp-logs'), title: 'File Logs', icon: 'file' },
  ],
  navItems: [
    { id: 'integration', label: 'Integrations', icon: 'link', path: '/integration/connections', order: 310 },
    { id: 'integ-api', label: 'API Endpoints', icon: 'code', path: '/integration/api-endpoints', order: 1, parent: 'integration' },
    { id: 'integ-keys', label: 'API Keys', icon: 'key', path: '/integration/api-keys', order: 2, parent: 'integration' },
    { id: 'integ-hooks', label: 'Webhooks', icon: 'send', path: '/integration/webhooks', order: 3, parent: 'integration' },
    { id: 'integ-hook-logs', label: 'Webhook Logs', icon: 'file-text', path: '/integration/webhook-logs', order: 4, parent: 'integration' },
    { id: 'integ-conn', label: 'Connections', icon: 'link', path: '/integration/connections', order: 5, parent: 'integration' },
    { id: 'integ-map', label: 'Mappings', icon: 'map', path: '/integration/mappings', order: 6, parent: 'integration' },
    { id: 'integ-sync', label: 'Sync Logs', icon: 'refresh-cw', path: '/integration/sync-logs', order: 7, parent: 'integration' },
    { id: 'integ-email', label: 'Email', icon: 'mail', path: '/integration/email', order: 8, parent: 'integration' },
    { id: 'integ-cal', label: 'Calendar', icon: 'calendar', path: '/integration/calendar', order: 9, parent: 'integration' },
    { id: 'integ-sftp', label: 'SFTP', icon: 'upload', path: '/integration/sftp', order: 10, parent: 'integration' },
    { id: 'integ-files', label: 'File Logs', icon: 'file', path: '/integration/sftp-logs', order: 11, parent: 'integration' },
  ],
  dashboardWidgets: [], settings: [], permissions: [
    { resource: 'integ.endpoint', actions: ['create','read','update','delete'], description: 'API endpoints' },
    { resource: 'integ.apiKey', actions: ['create','read','revoke'], description: 'API keys' },
    { resource: 'integ.webhook', actions: ['create','read','update','delete'], description: 'Webhooks' },
    { resource: 'integ.integration', actions: ['create','read','update','activate','deactivate'], description: 'Integration connections' },
    { resource: 'integ.email', actions: ['read','process'], description: 'Email integration' },
    { resource: 'integ.flatFile', actions: ['create','read','update'], description: 'Flat file configs' },
  ], workflows: [], importTypes: [], exportTypes: [], hooks: [],
};
