import type { ModuleManifest } from '../../core/types/module';

export const payrollManifest: ModuleManifest = {
  id: 'concrete.payroll',
  name: 'Payroll',
  description: 'Employee management, time entry, pay runs, gross-to-net calculation, tax withholding, workers compensation, and payroll reporting',
  version: '1.0.0',
  phase: 6,
  dependencies: ['concrete.gl', 'concrete.entity', 'concrete.job'],
  collections: [
    'payroll/employee', 'payroll/timeEntry', 'payroll/payRun', 'payroll/payCheck',
    'payroll/earning', 'payroll/deduction', 'payroll/benefit',
    'payroll/taxTable', 'payroll/taxFiling', 'payroll/workerComp',
  ],
  routes: [
    { path: '/payroll/employees', component: () => import('./views/employee-list'), title: 'Employees', icon: 'users' },
    { path: '/payroll/employees/new', component: () => import('./views/employee-form'), title: 'New Employee', icon: 'user-plus' },
    { path: '/payroll/employees/:id', component: () => import('./views/employee-form'), title: 'Edit Employee', icon: 'edit' },
    { path: '/payroll/time-entry', component: () => import('./views/time-entry'), title: 'Time Entry', icon: 'clock' },
    { path: '/payroll/pay-runs', component: () => import('./views/pay-run-list'), title: 'Pay Runs', icon: 'dollar-sign' },
    { path: '/payroll/pay-runs/new', component: () => import('./views/pay-run-form'), title: 'New Pay Run', icon: 'plus' },
    { path: '/payroll/pay-runs/:id', component: () => import('./views/pay-run-form'), title: 'Edit Pay Run', icon: 'edit' },
    { path: '/payroll/register', component: () => import('./views/register'), title: 'Payroll Register', icon: 'file-text' },
    { path: '/payroll/tax-filings', component: () => import('./views/tax-filings'), title: 'Tax Filings', icon: 'file' },
    { path: '/payroll/wc-codes', component: () => import('./views/wc-codes'), title: 'WC Codes', icon: 'shield' },
    { path: '/payroll/earnings-config', component: () => import('./views/earnings-config'), title: 'Earnings Config', icon: 'settings' },
    { path: '/payroll/pay-stub', component: () => import('./views/pay-stub'), title: 'Pay Stub', icon: 'printer' },
  ],
  navItems: [
    { id: 'payroll', label: 'Payroll', icon: 'dollar-sign', path: '/payroll/employees', order: 60 },
    { id: 'payroll-employees', label: 'Employees', icon: 'users', path: '/payroll/employees', order: 1, parent: 'payroll' },
    { id: 'payroll-time-entry', label: 'Time Entry', icon: 'clock', path: '/payroll/time-entry', order: 2, parent: 'payroll' },
    { id: 'payroll-pay-runs', label: 'Pay Runs', icon: 'dollar-sign', path: '/payroll/pay-runs', order: 3, parent: 'payroll' },
    { id: 'payroll-register', label: 'Register', icon: 'file-text', path: '/payroll/register', order: 4, parent: 'payroll' },
    { id: 'payroll-tax-filings', label: 'Tax Filings', icon: 'file', path: '/payroll/tax-filings', order: 5, parent: 'payroll' },
    { id: 'payroll-wc-codes', label: 'WC Codes', icon: 'shield', path: '/payroll/wc-codes', order: 6, parent: 'payroll' },
    { id: 'payroll-earnings-config', label: 'Config', icon: 'settings', path: '/payroll/earnings-config', order: 7, parent: 'payroll' },
  ],
  dashboardWidgets: [],
  settings: [],
  permissions: [
    { resource: 'payroll.employee', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Employee management' },
    { resource: 'payroll.timeEntry', actions: ['create', 'read', 'update', 'approve', 'export'], description: 'Time entry management' },
    { resource: 'payroll.payRun', actions: ['create', 'read', 'process', 'complete', 'void', 'export'], description: 'Pay run processing' },
    { resource: 'payroll.payCheck', actions: ['read', 'export'], description: 'Pay check viewing' },
    { resource: 'payroll.earning', actions: ['create', 'read', 'update', 'delete'], description: 'Earning type configuration' },
    { resource: 'payroll.deduction', actions: ['create', 'read', 'update', 'delete'], description: 'Deduction configuration' },
    { resource: 'payroll.benefit', actions: ['create', 'read', 'update', 'delete'], description: 'Benefit configuration' },
    { resource: 'payroll.taxTable', actions: ['create', 'read', 'update', 'delete'], description: 'Tax table management' },
    { resource: 'payroll.taxFiling', actions: ['create', 'read', 'update', 'export'], description: 'Tax filing management' },
    { resource: 'payroll.workerComp', actions: ['create', 'read', 'update', 'delete'], description: 'Workers compensation management' },
    { resource: 'payroll.report', actions: ['read', 'export'], description: 'Payroll reports (register, quarterly, earnings history)' },
  ],
  workflows: [],
  importTypes: [
    {
      id: 'payroll-time-entries',
      label: 'Import Time Entries',
      collection: 'payroll/timeEntry',
      fields: [
        { name: 'employeeId', type: 'string', required: true, label: 'Employee ID' },
        { name: 'jobId', type: 'string', label: 'Job ID' },
        { name: 'costCodeId', type: 'string', label: 'Cost Code ID' },
        { name: 'date', type: 'string', required: true, label: 'Date' },
        { name: 'hours', type: 'number', required: true, label: 'Hours' },
        { name: 'payType', type: 'string', required: true, label: 'Pay Type' },
        { name: 'workClassification', type: 'string', label: 'Work Classification' },
        { name: 'description', type: 'string', label: 'Description' },
      ],
      autoDetectHeaders: true,
    },
  ],
  exportTypes: [
    { id: 'payroll-register', label: 'Export Payroll Register', collection: 'payroll/payCheck', defaultFields: ['employeeId', 'grossPay', 'federalTax', 'stateTax', 'ficaSS', 'ficaMed', 'totalDeductions', 'netPay', 'hours', 'overtimeHours'] },
    { id: 'payroll-employees', label: 'Export Employees', collection: 'payroll/employee', defaultFields: ['firstName', 'lastName', 'ssn', 'status', 'department', 'payType', 'payRate', 'payFrequency'] },
  ],
  hooks: [],
};
