/**
 * UI components barrel export — re-exports from all component subdirectories.
 */

export {
  AppShell,
  TopNav,
  type NavItemConfig,
  Sidebar,
  type SidebarItem,
  ContentArea,
  SplitPane,
  type SplitPaneOptions,
  Grid,
  Stack,
} from './layout';

export {
  DataTable,
  type DataTableColumn,
  type DataTableConfig,
  KPICard,
  type KPICardConfig,
  ConcreteChart,
  type ChartDataset,
  type ChartConfig,
  TreeView,
  type TreeNode,
  Timeline,
  type TimelineItem,
  Badge,
  HealthDot,
  ProgressBar,
  type ProgressBarThresholds,
  BreakdownBar,
  type BreakdownSegment,
  EmptyState,
  type EmptyStateConfig,
  Stat,
  type StatConfig,
  Avatar,
  type AvatarConfig,
  Tooltip,
  type TooltipConfig,
} from './data-display';

export {
  Form,
  type FormConfig,
  TextField,
  type TextFieldConfig,
  NumberField,
  type NumberFieldConfig,
  CurrencyField,
  type CurrencyFieldConfig,
  DateField,
  type DateFieldConfig,
  SelectField,
  type SelectOption,
  type SelectFieldConfig,
  CheckboxField,
  type CheckboxFieldConfig,
  TextareaField,
  type TextareaFieldConfig,
  FileUpload,
  type FileUploadConfig,
  FormSection,
  type FormSectionConfig,
  FormActions,
  type FormActionsConfig,
  InlineEdit,
  type InlineEditConfig,
} from './forms';

export {
  Modal,
  type ModalConfig,
  SlidePanel,
  type SlidePanelConfig,
  Drawer,
  type DrawerConfig,
  ConfirmDialog,
  type ConfirmDialogConfig,
  Toast,
  type ToastConfig,
  CommandPalette,
  type CommandItem,
  type CommandPaletteConfig,
} from './overlays';

export {
  Breadcrumb,
  type BreadcrumbItem,
  FilterBar,
  type FilterDefinition,
  type FilterBarConfig,
  Pagination,
  type PaginationConfig,
  TabNav,
  type TabItem,
  type TabNavConfig,
} from './navigation';
