import type { ModuleManifest } from '../../core/types/module';

export const glManifest: ModuleManifest = {
  id: 'concrete.gl',
  name: 'General Ledger',
  description: 'Chart of Accounts, journal entries, trial balance, and GL reports',
  version: '1.0.0',
  phase: 1,
  dependencies: ['concrete.core'],
  collections: [
    'gl/account',
    'gl/journalEntry',
    'gl/journalLine',
    'gl/fiscalPeriod',
    'gl/recurringEntry',
    'gl/closingEntry',
  ],
  routes: [
    { path: '/gl', component: () => import('./views/gl-dashboard'), title: 'General Ledger' },
    { path: '/gl/accounts', component: () => import('./views/coa-list'), title: 'Chart of Accounts' },
    { path: '/gl/accounts/new', component: () => import('./views/coa-form'), title: 'New Account' },
    { path: '/gl/accounts/:id', component: () => import('./views/coa-form'), title: 'Edit Account' },
    { path: '/gl/journal', component: () => import('./views/je-list'), title: 'Journal Entries' },
    { path: '/gl/journal/new', component: () => import('./views/je-form'), title: 'New Journal Entry' },
    { path: '/gl/journal/:id', component: () => import('./views/je-form'), title: 'Edit Journal Entry' },
    { path: '/gl/trial-balance', component: () => import('./views/trial-balance'), title: 'Trial Balance' },
    { path: '/gl/detail', component: () => import('./views/gl-detail'), title: 'GL Detail' },
    { path: '/gl/recurring', component: () => import('./views/recurring-list'), title: 'Recurring Entries' },
    { path: '/gl/closing', component: () => import('./views/closing'), title: 'Closing Entries' },
  ],
  navItems: [
    { id: 'gl', label: 'General Ledger', path: '/gl', order: 10, icon: 'ledger' },
    { id: 'gl-accounts', label: 'Chart of Accounts', path: '/gl/accounts', order: 11, parent: 'gl' },
    { id: 'gl-journal', label: 'Journal Entries', path: '/gl/journal', order: 12, parent: 'gl' },
    { id: 'gl-trial-balance', label: 'Trial Balance', path: '/gl/trial-balance', order: 13, parent: 'gl' },
    { id: 'gl-detail', label: 'GL Detail', path: '/gl/detail', order: 14, parent: 'gl' },
    { id: 'gl-recurring', label: 'Recurring', path: '/gl/recurring', order: 15, parent: 'gl' },
    { id: 'gl-closing', label: 'Period Close', path: '/gl/closing', order: 16, parent: 'gl' },
  ],
  dashboardWidgets: [],
  settings: [],
  permissions: [
    { resource: 'gl.account', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Chart of Accounts' },
    { resource: 'gl.journalEntry', actions: ['create', 'read', 'update', 'delete', 'post', 'void', 'export'], description: 'Journal Entries' },
    { resource: 'gl.period', actions: ['read', 'close', 'reopen'], description: 'Fiscal Periods' },
    { resource: 'gl.report', actions: ['read', 'export'], description: 'GL Reports' },
  ],
  workflows: [],
  importTypes: [
    {
      id: 'gl-coa',
      label: 'Chart of Accounts',
      collection: 'gl/account',
      fields: [
        { name: 'number', type: 'string', required: true, label: 'Account Number' },
        { name: 'name', type: 'string', required: true, label: 'Account Name' },
        { name: 'type', type: 'enum', enum: ['asset', 'liability', 'equity', 'revenue', 'expense', 'costOfRevenue'], required: true, label: 'Account Type' },
        { name: 'parentNumber', type: 'string', label: 'Parent Account Number' },
        { name: 'description', type: 'string', label: 'Description' },
        { name: 'isActive', type: 'boolean', label: 'Active' },
      ],
    },
    {
      id: 'gl-journal',
      label: 'Journal Entries',
      collection: 'gl/journalEntry',
      fields: [
        { name: 'date', type: 'date', required: true, label: 'Date' },
        { name: 'reference', type: 'string', label: 'Reference' },
        { name: 'accountNumber', type: 'string', required: true, label: 'Account Number' },
        { name: 'debit', type: 'currency', label: 'Debit' },
        { name: 'credit', type: 'currency', label: 'Credit' },
        { name: 'description', type: 'string', label: 'Description' },
      ],
    },
  ],
  exportTypes: [
    { id: 'gl-coa-export', label: 'Chart of Accounts', collection: 'gl/account', defaultFields: ['number', 'name', 'type', 'parentId', 'description', 'isActive', 'normalBalance'] },
    { id: 'gl-je-export', label: 'Journal Entries', collection: 'gl/journalEntry', defaultFields: ['date', 'reference', 'description', 'status', 'totalDebit', 'totalCredit'] },
  ],
  hooks: [],
};
