export const bondingManifest = {
  id: 'concrete.bonding', name: 'Bonding & Insurance', description: 'Surety bonding, insurance policies, COI tracking, subcontractor compliance, and claims management.', version: '1.0.0', phase: 24, dependencies: ['concrete.job'],
  collections: ['bond/surety','bond/bond','bond/policy','bond/coi','bond/subInsurance','bond/wrapUp','bond/lossRun','bond/claim','bond/jobCost'],
  routes: [
    { path: '/bonding/sureties', component: () => import('./views/sureties'), title: 'Sureties', icon: 'building' },
    { path: '/bonding/bonds', component: () => import('./views/bonds'), title: 'Bonds', icon: 'shield' },
    { path: '/bonding/analysis', component: () => import('./views/analysis'), title: 'Bonding Analysis', icon: 'bar-chart' },
    { path: '/bonding/policies', component: () => import('./views/policies'), title: 'Policies', icon: 'file-text' },
    { path: '/bonding/alerts', component: () => import('./views/alerts'), title: 'Policy Alerts', icon: 'alert-triangle' },
    { path: '/bonding/coi', component: () => import('./views/coi'), title: 'COI Tracking', icon: 'award' },
    { path: '/bonding/sub-compliance', component: () => import('./views/sub-compliance'), title: 'Sub Compliance', icon: 'check-circle' },
    { path: '/bonding/wrap-up', component: () => import('./views/wrap-up'), title: 'OCIP/CCIP', icon: 'layers' },
    { path: '/bonding/loss-runs', component: () => import('./views/loss-runs'), title: 'Loss Runs', icon: 'trending-down' },
    { path: '/bonding/claims', component: () => import('./views/claims'), title: 'Claims', icon: 'alert-circle' },
    { path: '/bonding/job-costs', component: () => import('./views/job-costs'), title: 'Job Costs', icon: 'dollar-sign' },
  ],
  navItems: [
    { id: 'bonding', label: 'Bonding & Ins.', icon: 'shield', path: '/bonding/bonds', order: 240 },
    { id: 'bond-sureties', label: 'Sureties', icon: 'building', path: '/bonding/sureties', order: 1, parent: 'bonding' },
    { id: 'bond-bonds', label: 'Bonds', icon: 'shield', path: '/bonding/bonds', order: 2, parent: 'bonding' },
    { id: 'bond-analysis', label: 'Analysis', icon: 'bar-chart', path: '/bonding/analysis', order: 3, parent: 'bonding' },
    { id: 'bond-policies', label: 'Policies', icon: 'file-text', path: '/bonding/policies', order: 4, parent: 'bonding' },
    { id: 'bond-alerts', label: 'Alerts', icon: 'alert-triangle', path: '/bonding/alerts', order: 5, parent: 'bonding' },
    { id: 'bond-coi', label: 'COI', icon: 'award', path: '/bonding/coi', order: 6, parent: 'bonding' },
    { id: 'bond-sub', label: 'Sub Compliance', icon: 'check-circle', path: '/bonding/sub-compliance', order: 7, parent: 'bonding' },
    { id: 'bond-wrap', label: 'OCIP/CCIP', icon: 'layers', path: '/bonding/wrap-up', order: 8, parent: 'bonding' },
    { id: 'bond-loss', label: 'Loss Runs', icon: 'trending-down', path: '/bonding/loss-runs', order: 9, parent: 'bonding' },
    { id: 'bond-claims', label: 'Claims', icon: 'alert-circle', path: '/bonding/claims', order: 10, parent: 'bonding' },
    { id: 'bond-jobcost', label: 'Job Costs', icon: 'dollar-sign', path: '/bonding/job-costs', order: 11, parent: 'bonding' },
  ],
  dashboardWidgets: [], settings: [],
  permissions: [
    { resource: 'bond.surety', actions: ['create','read','update'], description: 'Surety management' },
    { resource: 'bond.bond', actions: ['create','read','release','export'], description: 'Bond issuance' },
    { resource: 'bond.policy', actions: ['create','read','update'], description: 'Insurance policies' },
    { resource: 'bond.coi', actions: ['create','read','revoke'], description: 'COI tracking' },
    { resource: 'bond.claim', actions: ['create','read','update','close'], description: 'Claims management' },
  ],
  workflows: [],
  importTypes: [{ id: 'bond-policies', label: 'Import Policies', collection: 'bond/policy', fields: [{ name: 'policyNumber', type: 'string', required: true, label: 'Policy #' },{ name: 'type', type: 'string', required: true, label: 'Type' },{ name: 'carrier', type: 'string', required: true, label: 'Carrier' },{ name: 'effectiveDate', type: 'string', required: true, label: 'Effective Date' },{ name: 'expirationDate', type: 'string', required: true, label: 'Expiration Date' }], autoDetectHeaders: true }],
  exportTypes: [{ id: 'bond-analysis-export', label: 'Export Bonding Analysis', collection: 'bond/bond', defaultFields: ['bondNumber','type','status','suretyName','jobName','amount','premium','effectiveDate','expirationDate'] }],
  hooks: [],
};
