export const taxComplianceManifest = {
  id: 'concrete.tax-compliance', name: 'Tax & Regulatory Compliance', description: 'Multi-jurisdiction tax compliance: federal/state payroll tax filing (941, 940, W-2, W-3), 1099 generation & e-filing, sales/use tax, contractor licenses, OCIP/CCIP, EEO/AA, prevailing wage, certified payroll, audit trail, tax rate management, and year-end processing.', version: '1.0.0', phase: 32, dependencies: [],
  collections: ['tax/federalFiling','tax/stateFiling','tax/multiState','tax/reciprocity','tax/form1099','tax/salesTax','tax/license','tax/ocipCcip','tax/eeoaa','tax/prevailingWage','tax/certifiedPayroll','tax/audit','tax/rate','tax/yearEnd'],
  routes: [
    { path: '/tax-compliance/federal-filings', component: () => import('./views/federal-filings'), title: 'Federal Filings', icon: 'file-text' },
    { path: '/tax-compliance/state-filings', component: () => import('./views/state-filings'), title: 'State Filings', icon: 'map-pin' },
    { path: '/tax-compliance/multi-state', component: () => import('./views/multi-state'), title: 'Multi-State', icon: 'globe' },
    { path: '/tax-compliance/form-1099', component: () => import('./views/form-1099'), title: '1099 Forms', icon: 'file' },
    { path: '/tax-compliance/sales-tax', component: () => import('./views/sales-tax'), title: 'Sales & Use Tax', icon: 'shopping-cart' },
    { path: '/tax-compliance/licenses', component: () => import('./views/licenses'), title: 'Licenses', icon: 'award' },
    { path: '/tax-compliance/ocip-ccip', component: () => import('./views/ocip-ccip'), title: 'OCIP/CCIP', icon: 'shield' },
    { path: '/tax-compliance/eeo-aa', component: () => import('./views/eeo-aa'), title: 'EEO/AA', icon: 'users' },
    { path: '/tax-compliance/prevailing-wage', component: () => import('./views/prevailing-wage'), title: 'Prevailing Wage', icon: 'dollar-sign' },
    { path: '/tax-compliance/certified-payroll', component: () => import('./views/certified-payroll'), title: 'Certified Payroll', icon: 'check-square' },
    { path: '/tax-compliance/audit-trail', component: () => import('./views/audit-trail'), title: 'Audit Trail', icon: 'activity' },
    { path: '/tax-compliance/tax-rates', component: () => import('./views/tax-rates'), title: 'Tax Rates', icon: 'percent' },
    { path: '/tax-compliance/year-end', component: () => import('./views/year-end'), title: 'Year-End', icon: 'calendar' },
  ],
  navItems: [
    { id: 'tax-compliance', label: 'Tax & Compliance', icon: 'shield', path: '/tax-compliance/federal-filings', order: 320 },
    { id: 'tax-federal', label: 'Federal Filings', icon: 'file-text', path: '/tax-compliance/federal-filings', order: 1, parent: 'tax-compliance' },
    { id: 'tax-state', label: 'State Filings', icon: 'map-pin', path: '/tax-compliance/state-filings', order: 2, parent: 'tax-compliance' },
    { id: 'tax-multi-state', label: 'Multi-State', icon: 'globe', path: '/tax-compliance/multi-state', order: 3, parent: 'tax-compliance' },
    { id: 'tax-1099', label: '1099 Forms', icon: 'file', path: '/tax-compliance/form-1099', order: 4, parent: 'tax-compliance' },
    { id: 'tax-sales', label: 'Sales & Use Tax', icon: 'shopping-cart', path: '/tax-compliance/sales-tax', order: 5, parent: 'tax-compliance' },
    { id: 'tax-licenses', label: 'Licenses', icon: 'award', path: '/tax-compliance/licenses', order: 6, parent: 'tax-compliance' },
    { id: 'tax-ocip', label: 'OCIP/CCIP', icon: 'shield', path: '/tax-compliance/ocip-ccip', order: 7, parent: 'tax-compliance' },
    { id: 'tax-eeo', label: 'EEO/AA', icon: 'users', path: '/tax-compliance/eeo-aa', order: 8, parent: 'tax-compliance' },
    { id: 'tax-prevailing', label: 'Prevailing Wage', icon: 'dollar-sign', path: '/tax-compliance/prevailing-wage', order: 9, parent: 'tax-compliance' },
    { id: 'tax-certified', label: 'Certified Payroll', icon: 'check-square', path: '/tax-compliance/certified-payroll', order: 10, parent: 'tax-compliance' },
    { id: 'tax-audit', label: 'Audit Trail', icon: 'activity', path: '/tax-compliance/audit-trail', order: 11, parent: 'tax-compliance' },
    { id: 'tax-rates', label: 'Tax Rates', icon: 'percent', path: '/tax-compliance/tax-rates', order: 12, parent: 'tax-compliance' },
    { id: 'tax-yearend', label: 'Year-End', icon: 'calendar', path: '/tax-compliance/year-end', order: 13, parent: 'tax-compliance' },
  ],
  dashboardWidgets: [], settings: [], permissions: [
    { resource: 'tax.federalFiling', actions: ['create','read','update','file','export'], description: 'Federal tax filings' },
    { resource: 'tax.stateFiling', actions: ['create','read','update','file','export'], description: 'State tax filings' },
    { resource: 'tax.multiState', actions: ['create','read','update'], description: 'Multi-state withholding records' },
    { resource: 'tax.reciprocity', actions: ['create','read','update'], description: 'Reciprocity agreements' },
    { resource: 'tax.form1099', actions: ['create','read','update','file','export'], description: '1099 forms' },
    { resource: 'tax.salesTax', actions: ['create','read','update','file'], description: 'Sales and use tax records' },
    { resource: 'tax.license', actions: ['create','read','update','delete'], description: 'Contractor licenses' },
    { resource: 'tax.ocipCcip', actions: ['create','read','update'], description: 'OCIP/CCIP programs' },
    { resource: 'tax.eeoaa', actions: ['create','read','update','submit'], description: 'EEO/AA reports' },
    { resource: 'tax.prevailingWage', actions: ['create','read','update','submit'], description: 'Prevailing wage reports' },
    { resource: 'tax.certifiedPayroll', actions: ['create','read','update','certify','submit'], description: 'Certified payroll reports' },
    { resource: 'tax.audit', actions: ['read','export'], description: 'Tax audit trail' },
    { resource: 'tax.rate', actions: ['create','read','update','import'], description: 'Tax rate management' },
    { resource: 'tax.yearEnd', actions: ['create','read','update','execute'], description: 'Year-end processing' },
  ], workflows: [], importTypes: [], exportTypes: [], hooks: [],
};
