export const bankingManifest = {
  id: 'concrete.banking', name: 'Bank Reconciliation & Cash Management', description: 'Bank reconciliation, cash position, projections, positive pay, ACH, checks, credit cards, petty cash, and trust accounts.', version: '1.0.0', phase: 25, dependencies: ['concrete.gl'],
  collections: ['bank/account','bank/statementLine','bank/reconciliation','bank/cashFlow','bank/positivePay','bank/achBatch','bank/check','bank/ccTransaction','bank/pettyCash','bank/pettyCashTxn','bank/trustAccount'],
  routes: [
    { path: '/banking/accounts', component: () => import('./views/accounts'), title: 'Bank Accounts', icon: 'credit-card' },
    { path: '/banking/statements', component: () => import('./views/statements'), title: 'Statements', icon: 'file-text' },
    { path: '/banking/reconciliation', component: () => import('./views/reconciliation'), title: 'Reconciliation', icon: 'check-square' },
    { path: '/banking/cash-position', component: () => import('./views/cash-position'), title: 'Cash Position', icon: 'dollar-sign' },
    { path: '/banking/projections', component: () => import('./views/projections'), title: 'Projections', icon: 'trending-up' },
    { path: '/banking/positive-pay', component: () => import('./views/positive-pay'), title: 'Positive Pay', icon: 'shield' },
    { path: '/banking/ach', component: () => import('./views/ach'), title: 'ACH', icon: 'send' },
    { path: '/banking/checks', component: () => import('./views/checks'), title: 'Checks', icon: 'edit-3' },
    { path: '/banking/credit-cards', component: () => import('./views/credit-cards'), title: 'Credit Cards', icon: 'credit-card' },
    { path: '/banking/petty-cash', component: () => import('./views/petty-cash'), title: 'Petty Cash', icon: 'pocket' },
    { path: '/banking/trust', component: () => import('./views/trust'), title: 'Trust Accounts', icon: 'lock' },
  ],
  navItems: [
    { id: 'banking', label: 'Banking', icon: 'credit-card', path: '/banking/accounts', order: 250 },
    { id: 'bank-accounts', label: 'Accounts', icon: 'credit-card', path: '/banking/accounts', order: 1, parent: 'banking' },
    { id: 'bank-statements', label: 'Statements', icon: 'file-text', path: '/banking/statements', order: 2, parent: 'banking' },
    { id: 'bank-recon', label: 'Reconciliation', icon: 'check-square', path: '/banking/reconciliation', order: 3, parent: 'banking' },
    { id: 'bank-cash', label: 'Cash Position', icon: 'dollar-sign', path: '/banking/cash-position', order: 4, parent: 'banking' },
    { id: 'bank-proj', label: 'Projections', icon: 'trending-up', path: '/banking/projections', order: 5, parent: 'banking' },
    { id: 'bank-pp', label: 'Positive Pay', icon: 'shield', path: '/banking/positive-pay', order: 6, parent: 'banking' },
    { id: 'bank-ach', label: 'ACH', icon: 'send', path: '/banking/ach', order: 7, parent: 'banking' },
    { id: 'bank-checks', label: 'Checks', icon: 'edit-3', path: '/banking/checks', order: 8, parent: 'banking' },
    { id: 'bank-cc', label: 'Credit Cards', icon: 'credit-card', path: '/banking/credit-cards', order: 9, parent: 'banking' },
    { id: 'bank-petty', label: 'Petty Cash', icon: 'pocket', path: '/banking/petty-cash', order: 10, parent: 'banking' },
    { id: 'bank-trust', label: 'Trust', icon: 'lock', path: '/banking/trust', order: 11, parent: 'banking' },
  ],
  dashboardWidgets: [], settings: [],
  permissions: [
    { resource: 'bank.account', actions: ['create','read','update'], description: 'Bank account management' },
    { resource: 'bank.reconciliation', actions: ['create','read','complete','approve'], description: 'Bank reconciliation' },
    { resource: 'bank.cashFlow', actions: ['create','read'], description: 'Cash flow projections' },
    { resource: 'bank.check', actions: ['create','read','void','reissue'], description: 'Check management' },
    { resource: 'bank.ach', actions: ['create','read','submit'], description: 'ACH management' },
  ],
  workflows: [], importTypes: [], exportTypes: [], hooks: [],
};
