import type { ModuleManifest } from '../../core/types/module';

export const serviceMgmtManifest: ModuleManifest = {
  id: 'concrete.serviceMgmt',
  name: 'Service Management',
  description: 'Service agreements, work orders, dispatch, technician tracking, preventive maintenance, customer equipment, billing, and profitability analysis',
  version: '1.0.0',
  phase: 20,
  dependencies: ['concrete.ar'],
  collections: [
    'service/serviceAgreement', 'service/workOrder', 'service/workOrderLine',
    'service/serviceCall', 'service/customerEquipment', 'service/preventiveMaintenance',
    'service/technicianTimeEntry',
  ],
  routes: [
    { path: '/service/agreements', component: () => import('./views/agreement-list'), title: 'Service Agreements', icon: 'file-text' },
    { path: '/service/agreements/new', component: () => import('./views/agreement-form'), title: 'New Agreement', icon: 'plus' },
    { path: '/service/agreements/:id', component: () => import('./views/agreement-form'), title: 'Edit Agreement', icon: 'edit' },
    { path: '/service/work-orders', component: () => import('./views/wo-list'), title: 'Work Orders', icon: 'clipboard' },
    { path: '/service/work-orders/new', component: () => import('./views/wo-form'), title: 'New Work Order', icon: 'plus' },
    { path: '/service/work-orders/:id', component: () => import('./views/wo-form'), title: 'Edit Work Order', icon: 'edit' },
    { path: '/service/dispatch', component: () => import('./views/dispatch'), title: 'Dispatch Board', icon: 'send' },
    { path: '/service/calls', component: () => import('./views/calls'), title: 'Service Calls', icon: 'phone' },
    { path: '/service/equipment', component: () => import('./views/equipment'), title: 'Customer Equipment', icon: 'tool' },
    { path: '/service/pm-schedules', component: () => import('./views/pm-schedules'), title: 'PM Schedules', icon: 'calendar' },
    { path: '/service/profitability', component: () => import('./views/profitability'), title: 'Profitability', icon: 'trending-up' },
    { path: '/service/history', component: () => import('./views/history'), title: 'Service History', icon: 'clock' },
  ],
  navItems: [
    { id: 'service', label: 'Service', icon: 'tool', path: '/service/agreements', order: 200 },
    { id: 'service-agreements', label: 'Agreements', icon: 'file-text', path: '/service/agreements', order: 1, parent: 'service' },
    { id: 'service-work-orders', label: 'Work Orders', icon: 'clipboard', path: '/service/work-orders', order: 2, parent: 'service' },
    { id: 'service-dispatch', label: 'Dispatch', icon: 'send', path: '/service/dispatch', order: 3, parent: 'service' },
    { id: 'service-calls', label: 'Calls', icon: 'phone', path: '/service/calls', order: 4, parent: 'service' },
    { id: 'service-equipment', label: 'Equipment', icon: 'tool', path: '/service/equipment', order: 5, parent: 'service' },
    { id: 'service-pm-schedules', label: 'PM Schedules', icon: 'calendar', path: '/service/pm-schedules', order: 6, parent: 'service' },
    { id: 'service-profitability', label: 'Profitability', icon: 'trending-up', path: '/service/profitability', order: 7, parent: 'service' },
  ],
  dashboardWidgets: [],
  settings: [],
  permissions: [
    { resource: 'service.agreement', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Service agreement management' },
    { resource: 'service.workOrder', actions: ['create', 'read', 'update', 'assign', 'complete', 'cancel', 'export'], description: 'Work order management' },
    { resource: 'service.dispatch', actions: ['read', 'assign'], description: 'Dispatch board' },
    { resource: 'service.call', actions: ['create', 'read', 'update', 'dispatch', 'resolve'], description: 'Service call management' },
    { resource: 'service.equipment', actions: ['create', 'read', 'update', 'retire', 'export'], description: 'Customer equipment registry' },
    { resource: 'service.pm', actions: ['create', 'read', 'update', 'complete', 'generate'], description: 'Preventive maintenance scheduling' },
    { resource: 'service.time', actions: ['create', 'read', 'update', 'export'], description: 'Technician time tracking' },
    { resource: 'service.billing', actions: ['read', 'bill', 'export'], description: 'Service billing' },
    { resource: 'service.report', actions: ['read', 'export'], description: 'Service reports (profitability, history)' },
  ],
  workflows: [],
  importTypes: [
    {
      id: 'service-work-orders',
      label: 'Import Work Orders',
      collection: 'service/workOrder',
      fields: [
        { name: 'number', type: 'string', required: true, label: 'Work Order Number' },
        { name: 'customerId', type: 'string', required: true, label: 'Customer ID' },
        { name: 'type', type: 'string', required: true, label: 'Type' },
        { name: 'priority', type: 'string', label: 'Priority' },
        { name: 'description', type: 'string', label: 'Description' },
        { name: 'scheduledDate', type: 'string', label: 'Scheduled Date' },
        { name: 'assignedTo', type: 'string', label: 'Assigned To' },
      ],
      autoDetectHeaders: true,
    },
  ],
  exportTypes: [
    { id: 'service-work-orders', label: 'Export Work Orders', collection: 'service/workOrder', defaultFields: ['number', 'customerId', 'type', 'status', 'priority', 'scheduledDate', 'assignedTo', 'totalAmount', 'billingStatus'] },
    { id: 'service-agreements', label: 'Export Service Agreements', collection: 'service/serviceAgreement', defaultFields: ['name', 'customerId', 'type', 'status', 'startDate', 'endDate', 'recurringAmount'] },
    { id: 'service-profitability', label: 'Export Profitability Report', collection: 'service/workOrder', defaultFields: ['number', 'customerId', 'laborTotal', 'materialTotal', 'totalAmount'] },
  ],
  hooks: [],
};
