import type { ModuleManifest } from '../../core/types/module';

export const arManifest: ModuleManifest = {
  id: 'concrete.ar',
  name: 'Accounts Receivable',
  description: 'Customer management, AR invoicing (progress, T&M, unit-price, cost-plus, lump-sum), AIA G702/G703 billing, payments, retainage tracking, billing schedules, aging reports, and overbilling analysis',
  version: '1.0.0',
  phase: 5,
  dependencies: ['concrete.gl', 'concrete.entity', 'concrete.job'],
  collections: [
    'ar/customer', 'ar/invoice', 'ar/invoiceLine', 'ar/payment',
    'ar/paymentApplication', 'ar/aiaApplication', 'ar/retainage',
    'ar/billingSchedule', 'ar/billingMilestone',
  ],
  routes: [
    { path: '/ar/customers', component: () => import('./views/customer-list'), title: 'Customers', icon: 'users' },
    { path: '/ar/customers/new', component: () => import('./views/customer-form'), title: 'New Customer', icon: 'user-plus' },
    { path: '/ar/customers/:id', component: () => import('./views/customer-form'), title: 'Edit Customer', icon: 'edit' },
    { path: '/ar/invoices', component: () => import('./views/invoice-list'), title: 'Invoices', icon: 'file-text' },
    { path: '/ar/invoices/new', component: () => import('./views/invoice-form'), title: 'New Invoice', icon: 'plus' },
    { path: '/ar/invoices/:id', component: () => import('./views/invoice-form'), title: 'Edit Invoice', icon: 'edit' },
    { path: '/ar/payments', component: () => import('./views/payments'), title: 'Payments', icon: 'credit-card' },
    { path: '/ar/aia', component: () => import('./views/aia-billing'), title: 'AIA Billing', icon: 'clipboard' },
    { path: '/ar/aging', component: () => import('./views/aging'), title: 'Customer Aging', icon: 'clock' },
    { path: '/ar/retainage', component: () => import('./views/retainage'), title: 'Retainage', icon: 'lock' },
    { path: '/ar/billing-schedules', component: () => import('./views/billing-schedules'), title: 'Billing Schedules', icon: 'calendar' },
  ],
  navItems: [
    { id: 'ar', label: 'AR', icon: 'dollar-sign', path: '/ar/customers', order: 50 },
    { id: 'ar-customers', label: 'Customers', icon: 'users', path: '/ar/customers', order: 1, parent: 'ar' },
    { id: 'ar-invoices', label: 'Invoices', icon: 'file-text', path: '/ar/invoices', order: 2, parent: 'ar' },
    { id: 'ar-payments', label: 'Payments', icon: 'credit-card', path: '/ar/payments', order: 3, parent: 'ar' },
    { id: 'ar-aia', label: 'AIA Billing', icon: 'clipboard', path: '/ar/aia', order: 4, parent: 'ar' },
    { id: 'ar-aging', label: 'Aging', icon: 'clock', path: '/ar/aging', order: 5, parent: 'ar' },
    { id: 'ar-retainage', label: 'Retainage', icon: 'lock', path: '/ar/retainage', order: 6, parent: 'ar' },
    { id: 'ar-billing-schedules', label: 'Billing Schedules', icon: 'calendar', path: '/ar/billing-schedules', order: 7, parent: 'ar' },
  ],
  dashboardWidgets: [],
  settings: [],
  permissions: [
    { resource: 'ar.customer', actions: ['create', 'read', 'update', 'delete', 'export'], description: 'Customer management' },
    { resource: 'ar.invoice', actions: ['create', 'read', 'update', 'send', 'void', 'export'], description: 'AR invoice management' },
    { resource: 'ar.payment', actions: ['create', 'read', 'apply', 'void', 'export'], description: 'Payment processing' },
    { resource: 'ar.aia', actions: ['create', 'read', 'update', 'submit', 'approve', 'export'], description: 'AIA G702/G703 billing' },
    { resource: 'ar.retainage', actions: ['create', 'read', 'release', 'export'], description: 'Retainage tracking' },
    { resource: 'ar.billingSchedule', actions: ['create', 'read', 'update', 'delete'], description: 'Billing schedule management' },
    { resource: 'ar.report', actions: ['read', 'export'], description: 'AR reports (aging, retainage aging, overbilling)' },
  ],
  workflows: [],
  importTypes: [
    {
      id: 'ar-receivables',
      label: 'Import AR Receivables',
      collection: 'ar/invoice',
      fields: [
        { name: 'customerName', type: 'string', required: true, label: 'Customer Name' },
        { name: 'invoiceNumber', type: 'string', required: true, label: 'Invoice Number' },
        { name: 'invoiceDate', type: 'string', required: true, label: 'Invoice Date' },
        { name: 'amount', type: 'number', required: true, label: 'Amount' },
        { name: 'dueDate', type: 'string', label: 'Due Date' },
        { name: 'billingType', type: 'string', label: 'Billing Type' },
        { name: 'retainageAmount', type: 'number', label: 'Retainage Amount' },
        { name: 'description', type: 'string', label: 'Description' },
      ],
      autoDetectHeaders: true,
    },
  ],
  exportTypes: [
    { id: 'ar-aging', label: 'Export AR Aging', collection: 'ar/invoice', defaultFields: ['customerId', 'invoiceNumber', 'invoiceDate', 'dueDate', 'amount', 'balanceDue', 'status'] },
    { id: 'ar-aia-billing', label: 'Export AIA Billing', collection: 'ar/aiaApplication', defaultFields: ['jobId', 'applicationNumber', 'periodTo', 'contractSum', 'totalCompleted', 'retainageAmount', 'status'] },
  ],
  hooks: [],
};
