export const mobileManifest = {
  id: 'concrete.mobile', name: 'Mobile & Field Operations', description: 'PWA with offline capability, mobile time entry, daily logs, inspections, material receipts, equipment logging, and digital signatures.', version: '1.0.0', phase: 26, dependencies: [],
  collections: ['mobile/timeEntry','mobile/dailyLog','mobile/inspection','mobile/receipt','mobile/equipmentLog','mobile/crewEntry','mobile/fieldWO','mobile/offlineQueue','mobile/notification','mobile/qrScan','mobile/signature'],
  routes: [
    { path: '/mobile/time-entry', component: () => import('./views/time-entry'), title: 'Time Entry', icon: 'clock' },
    { path: '/mobile/daily-logs', component: () => import('./views/daily-logs'), title: 'Daily Logs', icon: 'book' },
    { path: '/mobile/inspections', component: () => import('./views/inspections'), title: 'Inspections', icon: 'clipboard' },
    { path: '/mobile/receipts', component: () => import('./views/receipts'), title: 'Material Receipts', icon: 'package' },
    { path: '/mobile/equipment', component: () => import('./views/equipment'), title: 'Equipment Hours', icon: 'truck' },
    { path: '/mobile/crew-time', component: () => import('./views/crew-time'), title: 'Crew Time', icon: 'users' },
    { path: '/mobile/work-orders', component: () => import('./views/work-orders'), title: 'Field Work Orders', icon: 'tool' },
    { path: '/mobile/offline-queue', component: () => import('./views/offline-queue'), title: 'Offline Queue', icon: 'wifi-off' },
    { path: '/mobile/notifications', component: () => import('./views/notifications'), title: 'Notifications', icon: 'bell' },
    { path: '/mobile/qr-scanner', component: () => import('./views/qr-scanner'), title: 'QR Scanner', icon: 'camera' },
    { path: '/mobile/signatures', component: () => import('./views/signatures'), title: 'Signatures', icon: 'pen-tool' },
  ],
  navItems: [
    { id: 'mobile', label: 'Mobile', icon: 'smartphone', path: '/mobile/time-entry', order: 260 },
    { id: 'mob-time', label: 'Time Entry', icon: 'clock', path: '/mobile/time-entry', order: 1, parent: 'mobile' },
    { id: 'mob-logs', label: 'Daily Logs', icon: 'book', path: '/mobile/daily-logs', order: 2, parent: 'mobile' },
    { id: 'mob-insp', label: 'Inspections', icon: 'clipboard', path: '/mobile/inspections', order: 3, parent: 'mobile' },
    { id: 'mob-rcpt', label: 'Receipts', icon: 'package', path: '/mobile/receipts', order: 4, parent: 'mobile' },
    { id: 'mob-equip', label: 'Equipment', icon: 'truck', path: '/mobile/equipment', order: 5, parent: 'mobile' },
    { id: 'mob-crew', label: 'Crew Time', icon: 'users', path: '/mobile/crew-time', order: 6, parent: 'mobile' },
    { id: 'mob-wo', label: 'Work Orders', icon: 'tool', path: '/mobile/work-orders', order: 7, parent: 'mobile' },
    { id: 'mob-queue', label: 'Offline Queue', icon: 'wifi-off', path: '/mobile/offline-queue', order: 8, parent: 'mobile' },
    { id: 'mob-notif', label: 'Notifications', icon: 'bell', path: '/mobile/notifications', order: 9, parent: 'mobile' },
    { id: 'mob-qr', label: 'QR Scanner', icon: 'camera', path: '/mobile/qr-scanner', order: 10, parent: 'mobile' },
    { id: 'mob-sig', label: 'Signatures', icon: 'pen-tool', path: '/mobile/signatures', order: 11, parent: 'mobile' },
  ],
  dashboardWidgets: [], settings: [], permissions: [
    { resource: 'mobile.time', actions: ['create','read','approve','reject'], description: 'Mobile time entry' },
    { resource: 'mobile.dailyLog', actions: ['create','read','approve'], description: 'Daily logs' },
    { resource: 'mobile.inspection', actions: ['create','read'], description: 'Mobile inspections' },
    { resource: 'mobile.receipt', actions: ['create','read'], description: 'Material receipts' },
    { resource: 'mobile.workOrder', actions: ['create','read','start','complete'], description: 'Field work orders' },
  ], workflows: [], importTypes: [], exportTypes: [], hooks: [],
};
