export const syncManifest = {
  id: 'concrete.sync', name: 'Real-Time Sync & Offline-First', description: 'CRDT conflict resolution, WebSocket live updates, IndexedDB local storage, background sync, and bandwidth-aware replication.', version: '1.0.0', phase: 27, dependencies: [],
  collections: ['sync/crdt','sync/session','sync/wsConnection','sync/localDB','sync/conflict','sync/priority','sync/bandwidth','sync/selectiveRule','sync/statusIndicator','sync/checksum','sync/retry'],
  routes: [
    { path: '/sync/crdt', component: () => import('./views/crdt'), title: 'CRDT Records', icon: 'git-merge' },
    { path: '/sync/sessions', component: () => import('./views/sessions'), title: 'Sync Sessions', icon: 'refresh-cw' },
    { path: '/sync/connections', component: () => import('./views/connections'), title: 'Connections', icon: 'wifi' },
    { path: '/sync/local-db', component: () => import('./views/local-db'), title: 'Local DB', icon: 'database' },
    { path: '/sync/conflicts', component: () => import('./views/conflicts'), title: 'Conflicts', icon: 'alert-triangle' },
    { path: '/sync/priorities', component: () => import('./views/priorities'), title: 'Priorities', icon: 'list' },
    { path: '/sync/bandwidth', component: () => import('./views/bandwidth'), title: 'Bandwidth', icon: 'activity' },
    { path: '/sync/selective', component: () => import('./views/selective'), title: 'Selective Sync', icon: 'filter' },
    { path: '/sync/status', component: () => import('./views/status'), title: 'Sync Status', icon: 'check-circle' },
    { path: '/sync/checksums', component: () => import('./views/checksums'), title: 'Checksums', icon: 'hash' },
    { path: '/sync/retries', component: () => import('./views/retries'), title: 'Retries', icon: 'repeat' },
  ],
  navItems: [
    { id: 'sync', label: 'Sync', icon: 'refresh-cw', path: '/sync/status', order: 270 },
    { id: 'sync-crdt', label: 'CRDT', icon: 'git-merge', path: '/sync/crdt', order: 1, parent: 'sync' },
    { id: 'sync-sessions', label: 'Sessions', icon: 'refresh-cw', path: '/sync/sessions', order: 2, parent: 'sync' },
    { id: 'sync-conn', label: 'Connections', icon: 'wifi', path: '/sync/connections', order: 3, parent: 'sync' },
    { id: 'sync-db', label: 'Local DB', icon: 'database', path: '/sync/local-db', order: 4, parent: 'sync' },
    { id: 'sync-conflicts', label: 'Conflicts', icon: 'alert-triangle', path: '/sync/conflicts', order: 5, parent: 'sync' },
    { id: 'sync-prio', label: 'Priorities', icon: 'list', path: '/sync/priorities', order: 6, parent: 'sync' },
    { id: 'sync-bw', label: 'Bandwidth', icon: 'activity', path: '/sync/bandwidth', order: 7, parent: 'sync' },
    { id: 'sync-sel', label: 'Selective', icon: 'filter', path: '/sync/selective', order: 8, parent: 'sync' },
    { id: 'sync-status', label: 'Status', icon: 'check-circle', path: '/sync/status', order: 9, parent: 'sync' },
    { id: 'sync-chk', label: 'Checksums', icon: 'hash', path: '/sync/checksums', order: 10, parent: 'sync' },
    { id: 'sync-retry', label: 'Retries', icon: 'repeat', path: '/sync/retries', order: 11, parent: 'sync' },
  ],
  dashboardWidgets: [], settings: [], permissions: [
    { resource: 'sync.crdt', actions: ['read','resolve'], description: 'CRDT records' },
    { resource: 'sync.session', actions: ['read'], description: 'Sync sessions' },
    { resource: 'sync.conflict', actions: ['read','resolve'], description: 'Conflict resolution' },
    { resource: 'sync.config', actions: ['read','update'], description: 'Sync configuration' },
  ], workflows: [], importTypes: [], exportTypes: [], hooks: [],
};
