/**
 * Accounts Payable module collection schemas.
 * Phase 4: vendor, invoice, invoiceLine, payment, paymentLine,
 * lienWaiver, complianceCert, retention.
 */

import type { SchemaDef } from '../../types/schema';

export const apSchemas: SchemaDef[] = [
  {
    collection: 'ap/vendor',
    module: 'ap',
    version: 2,
    fields: [
      { name: 'name', type: 'string', required: true, label: 'Vendor Name' },
      { name: 'code', type: 'string', label: 'Vendor Code' },
      { name: 'taxId', type: 'string', label: 'Tax ID (EIN/SSN)' },
      { name: 'vendorType', type: 'enum', enum: ['subcontractor', 'supplier', 'professional', 'utility', 'other'], label: 'Vendor Type' },
      { name: 'status', type: 'enum', enum: ['active', 'inactive', 'hold'], label: 'Status' },
      { name: 'address', type: 'string', label: 'Address' },
      { name: 'city', type: 'string', label: 'City' },
      { name: 'state', type: 'string', label: 'State' },
      { name: 'zip', type: 'string', label: 'Zip' },
      { name: 'country', type: 'string', label: 'Country' },
      { name: 'phone', type: 'string', label: 'Phone' },
      { name: 'email', type: 'string', label: 'Email' },
      { name: 'website', type: 'string', label: 'Website' },
      { name: 'contactName', type: 'string', label: 'Primary Contact' },
      { name: 'contactPhone', type: 'string', label: 'Contact Phone' },
      { name: 'contactEmail', type: 'string', label: 'Contact Email' },
      { name: 'defaultTerms', type: 'string', label: 'Default Terms' },
      { name: 'defaultPaymentMethod', type: 'enum', enum: ['check', 'ach', 'wire', 'credit-card'], label: 'Default Payment Method' },
      { name: 'is1099', type: 'boolean', label: '1099 Vendor' },
      { name: 'form1099Type', type: 'enum', enum: ['MISC', 'NEC', 'INT', 'DIV', 'R', 'S'], label: '1099 Form Type' },
      { name: 'insuranceRequired', type: 'boolean', label: 'Insurance Required' },
      { name: 'bondRequired', type: 'boolean', label: 'Bond Required' },
      { name: 'entityId', type: 'id', label: 'Entity' },
      { name: 'notes', type: 'string', label: 'Notes' },
      { name: 'ytdPayments', type: 'currency', label: 'YTD Payments' },
      { name: 'ytd1099Amount', type: 'currency', label: 'YTD 1099 Amount' },
    ],
    relations: [
      { foreignKey: 'entityId', collection: 'entity/entity', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'ap/invoice',
    module: 'ap',
    version: 2,
    fields: [
      { name: 'vendorId', type: 'id', required: true, label: 'Vendor' },
      { name: 'invoiceNumber', type: 'string', required: true, label: 'Invoice Number' },
      { name: 'invoiceDate', type: 'date', required: true, label: 'Invoice Date' },
      { name: 'dueDate', type: 'date', label: 'Due Date' },
      { name: 'receivedDate', type: 'date', label: 'Received Date' },
      { name: 'terms', type: 'string', label: 'Payment Terms' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'amount', type: 'currency', required: true, label: 'Amount' },
      { name: 'taxAmount', type: 'currency', label: 'Tax Amount' },
      { name: 'retentionAmount', type: 'currency', label: 'Retention Amount' },
      { name: 'netAmount', type: 'currency', label: 'Net Amount' },
      { name: 'paidAmount', type: 'currency', label: 'Paid Amount' },
      { name: 'balanceDue', type: 'currency', label: 'Balance Due' },
      { name: 'status', type: 'enum', enum: ['draft', 'pending', 'approved', 'partial', 'paid', 'voided'], label: 'Status' },
      { name: 'approvedBy', type: 'string', label: 'Approved By' },
      { name: 'approvedAt', type: 'date', label: 'Approved At' },
      { name: 'jobId', type: 'id', label: 'Job' },
      { name: 'entityId', type: 'id', label: 'Entity' },
      { name: 'duplicateFlag', type: 'boolean', label: 'Possible Duplicate' },
      { name: 'duplicateOfId', type: 'id', label: 'Duplicate Of' },
    ],
    relations: [
      { foreignKey: 'vendorId', collection: 'ap/vendor', type: 'belongsTo', cascade: 'restrict' },
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'nullify' },
      { foreignKey: 'entityId', collection: 'entity/entity', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'ap/invoiceLine',
    module: 'ap',
    version: 2,
    fields: [
      { name: 'invoiceId', type: 'id', required: true, label: 'Invoice' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'amount', type: 'currency', required: true, label: 'Amount' },
      { name: 'jobId', type: 'id', label: 'Job' },
      { name: 'costCodeId', type: 'id', label: 'Cost Code' },
      { name: 'costType', type: 'enum', enum: ['labor', 'material', 'subcontract', 'equipment', 'other', 'overhead'], label: 'Cost Type' },
      { name: 'glAccountId', type: 'id', label: 'GL Account' },
      { name: 'quantity', type: 'number', label: 'Quantity' },
      { name: 'unitCost', type: 'currency', label: 'Unit Cost' },
    ],
    relations: [
      { foreignKey: 'invoiceId', collection: 'ap/invoice', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'nullify' },
      { foreignKey: 'costCodeId', collection: 'job/costCode', type: 'belongsTo', cascade: 'nullify' },
      { foreignKey: 'glAccountId', collection: 'gl/account', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'ap/payment',
    module: 'ap',
    version: 2,
    fields: [
      { name: 'vendorId', type: 'id', required: true, label: 'Vendor' },
      { name: 'date', type: 'date', required: true, label: 'Payment Date' },
      { name: 'amount', type: 'currency', required: true, label: 'Amount' },
      { name: 'method', type: 'enum', enum: ['check', 'ach', 'wire', 'credit-card'], label: 'Method' },
      { name: 'referenceNumber', type: 'string', label: 'Reference Number' },
      { name: 'memo', type: 'string', label: 'Memo' },
      { name: 'entityId', type: 'id', label: 'Entity' },
      { name: 'status', type: 'enum', enum: ['pending', 'processed', 'voided'], label: 'Status' },
    ],
    relations: [
      { foreignKey: 'vendorId', collection: 'ap/vendor', type: 'belongsTo', cascade: 'restrict' },
      { foreignKey: 'entityId', collection: 'entity/entity', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'ap/paymentLine',
    module: 'ap',
    version: 2,
    fields: [
      { name: 'paymentId', type: 'id', required: true, label: 'Payment' },
      { name: 'invoiceId', type: 'id', required: true, label: 'Invoice' },
      { name: 'amount', type: 'currency', required: true, label: 'Amount Applied' },
      { name: 'retentionAmount', type: 'currency', label: 'Retention Amount' },
      { name: 'discountAmount', type: 'currency', label: 'Discount Amount' },
    ],
    relations: [
      { foreignKey: 'paymentId', collection: 'ap/payment', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'invoiceId', collection: 'ap/invoice', type: 'belongsTo', cascade: 'restrict' },
    ],
  },
  {
    collection: 'ap/lienWaiver',
    module: 'ap',
    version: 2,
    fields: [
      { name: 'vendorId', type: 'id', required: true, label: 'Vendor' },
      { name: 'jobId', type: 'id', label: 'Job' },
      { name: 'type', type: 'enum', enum: ['conditional_partial', 'unconditional_partial', 'conditional_final', 'unconditional_final'], label: 'Waiver Type' },
      { name: 'status', type: 'enum', enum: ['requested', 'received', 'expired'], label: 'Status' },
      { name: 'amount', type: 'currency', label: 'Through Amount' },
      { name: 'throughDate', type: 'date', label: 'Through Date' },
      { name: 'receivedDate', type: 'date', label: 'Received Date' },
      { name: 'paymentId', type: 'id', label: 'Associated Payment' },
      { name: 'description', type: 'string', label: 'Description' },
    ],
    relations: [
      { foreignKey: 'vendorId', collection: 'ap/vendor', type: 'belongsTo', cascade: 'restrict' },
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'nullify' },
      { foreignKey: 'paymentId', collection: 'ap/payment', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'ap/complianceCert',
    module: 'ap',
    version: 2,
    fields: [
      { name: 'vendorId', type: 'id', required: true, label: 'Vendor' },
      { name: 'certType', type: 'enum', enum: ['insurance_gl', 'insurance_auto', 'insurance_umbrella', 'insurance_wc', 'license', 'bond', 'other'], required: true, label: 'Certificate Type' },
      { name: 'policyNumber', type: 'string', label: 'Policy/License Number' },
      { name: 'carrier', type: 'string', label: 'Carrier / Issuer' },
      { name: 'agent', type: 'string', label: 'Agent' },
      { name: 'effectiveDate', type: 'date', label: 'Effective Date' },
      { name: 'expirationDate', type: 'date', label: 'Expiration Date' },
      { name: 'coverageAmount', type: 'currency', label: 'Coverage Amount' },
      { name: 'status', type: 'enum', enum: ['valid', 'expired', 'pending', 'revoked'], label: 'Status' },
      { name: 'jobId', type: 'id', label: 'Job' },
    ],
    relations: [
      { foreignKey: 'vendorId', collection: 'ap/vendor', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'ap/retention',
    module: 'ap',
    version: 2,
    fields: [
      { name: 'invoiceId', type: 'id', required: true, label: 'Invoice' },
      { name: 'vendorId', type: 'id', required: true, label: 'Vendor' },
      { name: 'jobId', type: 'id', label: 'Job' },
      { name: 'amount', type: 'currency', required: true, label: 'Retained Amount' },
      { name: 'retentionPct', type: 'number', label: 'Retention %' },
      { name: 'releasedAmount', type: 'currency', label: 'Released Amount' },
      { name: 'remainingAmount', type: 'currency', label: 'Remaining Amount' },
      { name: 'releaseDate', type: 'date', label: 'Release Date' },
      { name: 'status', type: 'enum', enum: ['held', 'partial', 'released'], label: 'Status' },
    ],
    relations: [
      { foreignKey: 'invoiceId', collection: 'ap/invoice', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'vendorId', collection: 'ap/vendor', type: 'belongsTo', cascade: 'restrict' },
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
];
