/**
 * General Ledger module collection schemas.
 * account, journalEntry, journalLine, fiscalPeriod, recurringEntry, closingEntry.
 */

import type { SchemaDef } from '../../types/schema';

export const glSchemas: SchemaDef[] = [
  {
    collection: 'gl/account',
    module: 'gl',
    version: 2,
    fields: [
      { name: 'number', type: 'string', required: true, label: 'Account Number' },
      { name: 'name', type: 'string', required: true, label: 'Account Name' },
      {
        name: 'type',
        type: 'enum',
        enum: ['asset', 'liability', 'equity', 'revenue', 'expense', 'costOfRevenue'],
        required: true,
        label: 'Account Type',
      },
      {
        name: 'normalBalance',
        type: 'enum',
        enum: ['debit', 'credit'],
        required: true,
        label: 'Normal Balance',
      },
      { name: 'parentId', type: 'id', label: 'Parent Account' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'isActive', type: 'boolean', label: 'Active' },
      { name: 'depth', type: 'number', label: 'Hierarchy Depth' },
      { name: 'path', type: 'string', label: 'Account Path' },
      { name: 'isSummary', type: 'boolean', label: 'Summary Account' },
    ],
    relations: [
      { foreignKey: 'parentId', collection: 'gl/account', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'gl/journalEntry',
    module: 'gl',
    version: 2,
    fields: [
      { name: 'entryNumber', type: 'string', required: true, label: 'Entry Number' },
      { name: 'date', type: 'date', required: true, label: 'Entry Date' },
      { name: 'reference', type: 'string', label: 'Reference' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'status', type: 'enum', enum: ['draft', 'posted', 'voided'], label: 'Status' },
      { name: 'totalDebit', type: 'currency', label: 'Total Debit' },
      { name: 'totalCredit', type: 'currency', label: 'Total Credit' },
      { name: 'postedAt', type: 'date', label: 'Posted At' },
      { name: 'voidedAt', type: 'date', label: 'Voided At' },
      { name: 'voidReason', type: 'string', label: 'Void Reason' },
      { name: 'sourceModule', type: 'string', label: 'Source Module' },
      { name: 'sourceId', type: 'string', label: 'Source ID' },
      { name: 'fiscalPeriodId', type: 'id', label: 'Fiscal Period' },
      { name: 'isAutoGenerated', type: 'boolean', label: 'Auto-Generated' },
    ],
    relations: [
      { foreignKey: 'fiscalPeriodId', collection: 'gl/fiscalPeriod', type: 'belongsTo', cascade: 'restrict' },
    ],
  },
  {
    collection: 'gl/journalLine',
    module: 'gl',
    version: 2,
    fields: [
      { name: 'journalEntryId', type: 'id', required: true, label: 'Journal Entry' },
      { name: 'accountId', type: 'id', required: true, label: 'Account' },
      { name: 'accountNumber', type: 'string', label: 'Account Number' },
      { name: 'accountName', type: 'string', label: 'Account Name' },
      { name: 'debit', type: 'currency', label: 'Debit' },
      { name: 'credit', type: 'currency', label: 'Credit' },
      { name: 'description', type: 'string', label: 'Line Description' },
      { name: 'lineOrder', type: 'number', label: 'Line Order' },
    ],
    relations: [
      { foreignKey: 'journalEntryId', collection: 'gl/journalEntry', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'accountId', collection: 'gl/account', type: 'belongsTo', cascade: 'restrict' },
    ],
  },
  {
    collection: 'gl/fiscalPeriod',
    module: 'gl',
    version: 2,
    fields: [
      { name: 'name', type: 'string', required: true, label: 'Period Name' },
      { name: 'year', type: 'number', required: true, label: 'Fiscal Year' },
      { name: 'month', type: 'number', label: 'Month Number' },
      { name: 'startDate', type: 'date', required: true, label: 'Start Date' },
      { name: 'endDate', type: 'date', required: true, label: 'End Date' },
      { name: 'status', type: 'enum', enum: ['open', 'closed', 'locked'], label: 'Status' },
      { name: 'closedAt', type: 'date', label: 'Closed At' },
    ],
    relations: [],
  },
  {
    collection: 'gl/recurringEntry',
    module: 'gl',
    version: 2,
    fields: [
      { name: 'name', type: 'string', required: true, label: 'Name' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'frequency', type: 'enum', enum: ['daily', 'weekly', 'monthly', 'quarterly', 'yearly'], required: true, label: 'Frequency' },
      { name: 'isActive', type: 'boolean', label: 'Active' },
      { name: 'nextRunDate', type: 'date', label: 'Next Run Date' },
      { name: 'lastRunDate', type: 'date', label: 'Last Run Date' },
      { name: 'endDate', type: 'date', label: 'End Date' },
      { name: 'templateLines', type: 'array', label: 'Template Lines' },
      { name: 'runCount', type: 'number', label: 'Run Count' },
    ],
    relations: [],
  },
  {
    collection: 'gl/closingEntry',
    module: 'gl',
    version: 2,
    fields: [
      { name: 'fiscalPeriodId', type: 'id', required: true, label: 'Fiscal Period' },
      { name: 'journalEntryId', type: 'id', required: true, label: 'Journal Entry' },
      { name: 'type', type: 'enum', enum: ['income-summary', 'retained-earnings'], label: 'Closing Type' },
      { name: 'periodName', type: 'string', label: 'Period Name' },
      { name: 'totalAmount', type: 'currency', label: 'Total Amount' },
    ],
    relations: [
      { foreignKey: 'fiscalPeriodId', collection: 'gl/fiscalPeriod', type: 'belongsTo', cascade: 'restrict' },
      { foreignKey: 'journalEntryId', collection: 'gl/journalEntry', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
];
