/**
 * Job Costing module collection schemas (Phase 3 — Job Costing Foundation).
 * job, costCode, costType, budget, budgetLine, actualCost, committedCost, wip, changeOrder.
 */

import type { SchemaDef } from '../../types/schema';

export const jobSchemas: SchemaDef[] = [
  {
    collection: 'job/job',
    module: 'job',
    version: 2,
    fields: [
      { name: 'number', type: 'string', required: true, label: 'Job Number' },
      { name: 'name', type: 'string', required: true, label: 'Job Name' },
      {
        name: 'type',
        type: 'enum',
        enum: ['lump_sum', 'time_material', 'cost_plus', 'unit_price', 'design_build', 'gmp'],
        required: true,
        label: 'Job Type',
      },
      {
        name: 'status',
        type: 'enum',
        enum: ['bidding', 'awarded', 'active', 'complete', 'closed'],
        label: 'Status',
      },
      { name: 'customerId', type: 'id', label: 'Customer' },
      { name: 'entityId', type: 'id', label: 'Entity' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'contractAmount', type: 'currency', label: 'Contract Amount' },
      { name: 'startDate', type: 'date', label: 'Start Date' },
      { name: 'endDate', type: 'date', label: 'End Date' },
      { name: 'completionDate', type: 'date', label: 'Actual Completion Date' },
      { name: 'ownerName', type: 'string', label: 'Owner Name' },
      { name: 'address', type: 'string', label: 'Job Address' },
      { name: 'city', type: 'string', label: 'City' },
      { name: 'state', type: 'string', label: 'State' },
      { name: 'zip', type: 'string', label: 'ZIP' },
      { name: 'projectManagerId', type: 'string', label: 'Project Manager' },
      { name: 'superintendentId', type: 'string', label: 'Superintendent' },
      { name: 'retentionPct', type: 'percentage', label: 'Retention %' },
      { name: 'percentComplete', type: 'percentage', label: '% Complete' },
      { name: 'totalBudget', type: 'currency', label: 'Total Budget' },
      { name: 'totalActualCost', type: 'currency', label: 'Total Actual Cost' },
      { name: 'totalCommitted', type: 'currency', label: 'Total Committed' },
      { name: 'totalBilled', type: 'currency', label: 'Total Billed' },
    ],
    relations: [
      { foreignKey: 'customerId', collection: 'ar/customer', type: 'belongsTo', cascade: 'nullify' },
      { foreignKey: 'entityId', collection: 'entity/entity', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'job/costCode',
    module: 'job',
    version: 2,
    fields: [
      { name: 'code', type: 'string', required: true, label: 'Cost Code' },
      { name: 'description', type: 'string', required: true, label: 'Description' },
      { name: 'parentId', type: 'id', label: 'Parent Cost Code' },
      { name: 'isStandard', type: 'boolean', label: 'Standard (CSI MasterFormat)' },
      { name: 'depth', type: 'number', label: 'Depth' },
    ],
    relations: [
      { foreignKey: 'parentId', collection: 'job/costCode', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'job/budget',
    module: 'job',
    version: 2,
    fields: [
      { name: 'jobId', type: 'id', required: true, label: 'Job' },
      { name: 'name', type: 'string', required: true, label: 'Budget Name' },
      { name: 'status', type: 'enum', enum: ['draft', 'approved', 'revised'], label: 'Status' },
      { name: 'revision', type: 'number', label: 'Revision Number' },
      { name: 'totalAmount', type: 'currency', label: 'Total Amount' },
      { name: 'approvedAt', type: 'date', label: 'Approved Date' },
      { name: 'approvedBy', type: 'string', label: 'Approved By' },
    ],
    relations: [
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
  {
    collection: 'job/budgetLine',
    module: 'job',
    version: 2,
    fields: [
      { name: 'budgetId', type: 'id', required: true, label: 'Budget' },
      { name: 'jobId', type: 'id', required: true, label: 'Job' },
      { name: 'costCodeId', type: 'id', required: true, label: 'Cost Code' },
      {
        name: 'costType',
        type: 'enum',
        enum: ['labor', 'material', 'subcontract', 'equipment', 'other', 'overhead'],
        required: true,
        label: 'Cost Type',
      },
      { name: 'amount', type: 'currency', required: true, label: 'Budget Amount' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'quantity', type: 'number', label: 'Quantity' },
      { name: 'unitCost', type: 'currency', label: 'Unit Cost' },
    ],
    relations: [
      { foreignKey: 'budgetId', collection: 'job/budget', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'costCodeId', collection: 'job/costCode', type: 'belongsTo', cascade: 'restrict' },
    ],
  },
  {
    collection: 'job/actualCost',
    module: 'job',
    version: 1,
    fields: [
      { name: 'jobId', type: 'id', required: true, label: 'Job' },
      { name: 'costCodeId', type: 'id', required: true, label: 'Cost Code' },
      {
        name: 'costType',
        type: 'enum',
        enum: ['labor', 'material', 'subcontract', 'equipment', 'other', 'overhead'],
        required: true,
        label: 'Cost Type',
      },
      { name: 'date', type: 'date', required: true, label: 'Date' },
      { name: 'amount', type: 'currency', required: true, label: 'Amount' },
      { name: 'description', type: 'string', label: 'Description' },
      {
        name: 'source',
        type: 'enum',
        enum: ['ap', 'payroll', 'equipment', 'je', 'manual'],
        label: 'Source',
      },
      { name: 'sourceId', type: 'string', label: 'Source Reference ID' },
      { name: 'vendorName', type: 'string', label: 'Vendor Name' },
      { name: 'invoiceNumber', type: 'string', label: 'Invoice Number' },
      { name: 'quantity', type: 'number', label: 'Quantity' },
      { name: 'unitCost', type: 'currency', label: 'Unit Cost' },
    ],
    relations: [
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'costCodeId', collection: 'job/costCode', type: 'belongsTo', cascade: 'restrict' },
    ],
  },
  {
    collection: 'job/committedCost',
    module: 'job',
    version: 1,
    fields: [
      { name: 'jobId', type: 'id', required: true, label: 'Job' },
      { name: 'costCodeId', type: 'id', required: true, label: 'Cost Code' },
      {
        name: 'costType',
        type: 'enum',
        enum: ['labor', 'material', 'subcontract', 'equipment', 'other', 'overhead'],
        required: true,
        label: 'Cost Type',
      },
      {
        name: 'type',
        type: 'enum',
        enum: ['purchase_order', 'subcontract'],
        required: true,
        label: 'Commitment Type',
      },
      { name: 'referenceNumber', type: 'string', label: 'PO/Contract Number' },
      { name: 'vendorName', type: 'string', label: 'Vendor/Sub Name' },
      { name: 'amount', type: 'currency', required: true, label: 'Committed Amount' },
      { name: 'invoicedAmount', type: 'currency', label: 'Invoiced to Date' },
      { name: 'remainingAmount', type: 'currency', label: 'Remaining' },
      { name: 'date', type: 'date', required: true, label: 'Date' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'status', type: 'enum', enum: ['open', 'partial', 'closed', 'cancelled'], label: 'Status' },
    ],
    relations: [
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'costCodeId', collection: 'job/costCode', type: 'belongsTo', cascade: 'restrict' },
    ],
  },
  {
    collection: 'job/wip',
    module: 'job',
    version: 2,
    fields: [
      { name: 'jobId', type: 'id', required: true, label: 'Job' },
      { name: 'periodId', type: 'id', label: 'Fiscal Period' },
      { name: 'periodName', type: 'string', label: 'Period Name' },
      { name: 'contractAmount', type: 'currency', label: 'Contract Amount' },
      { name: 'totalBudget', type: 'currency', label: 'Total Budget' },
      { name: 'actualCostToDate', type: 'currency', label: 'Actual Cost to Date' },
      { name: 'estimateToComplete', type: 'currency', label: 'Estimate to Complete' },
      { name: 'estimateAtCompletion', type: 'currency', label: 'Estimate at Completion' },
      { name: 'percentComplete', type: 'percentage', label: '% Complete' },
      { name: 'earnedRevenue', type: 'currency', label: 'Earned Revenue' },
      { name: 'billedToDate', type: 'currency', label: 'Billed to Date' },
      { name: 'overUnderBilling', type: 'currency', label: 'Over/Under Billing' },
      { name: 'projectedGrossProfit', type: 'currency', label: 'Projected Gross Profit' },
      { name: 'projectedMarginPct', type: 'percentage', label: 'Projected Margin %' },
    ],
    relations: [
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'periodId', collection: 'gl/fiscalPeriod', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'job/changeOrder',
    module: 'job',
    version: 1,
    fields: [
      { name: 'jobId', type: 'id', required: true, label: 'Job' },
      { name: 'number', type: 'string', required: true, label: 'CO Number' },
      { name: 'description', type: 'string', required: true, label: 'Description' },
      { name: 'amount', type: 'currency', required: true, label: 'Amount' },
      { name: 'status', type: 'enum', enum: ['pending', 'approved', 'rejected'], label: 'Status' },
      { name: 'date', type: 'date', label: 'Date' },
      { name: 'approvedAt', type: 'date', label: 'Approved Date' },
    ],
    relations: [
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
];
