/**
 * Project Management module collection schemas.
 * Phase 18: project, milestone, task, taskDependency, dailyLog, rfi,
 * submittal, meetingMinutes, weatherDelay, resourceAllocation.
 */

import type { SchemaDef } from '../../types/schema';

export const projectSchemas: SchemaDef[] = [
  {
    collection: 'project/project',
    module: 'project',
    version: 1,
    fields: [
      { name: 'name', type: 'string', required: true, label: 'Project Name' },
      { name: 'jobId', type: 'id', label: 'Job' },
      { name: 'status', type: 'enum', enum: ['planning', 'active', 'on_hold', 'completed', 'cancelled'], label: 'Status' },
      { name: 'startDate', type: 'date', label: 'Start Date' },
      { name: 'endDate', type: 'date', label: 'End Date' },
      { name: 'baselineStartDate', type: 'date', label: 'Baseline Start Date' },
      { name: 'baselineEndDate', type: 'date', label: 'Baseline End Date' },
      { name: 'manager', type: 'string', label: 'Project Manager' },
      { name: 'percentComplete', type: 'number', label: 'Percent Complete' },
      { name: 'percentCompleteMethod', type: 'enum', enum: ['cost', 'units', 'manual'], label: 'Percent Complete Method' },
      { name: 'budgetedCost', type: 'currency', label: 'Budgeted Cost' },
      { name: 'actualCost', type: 'currency', label: 'Actual Cost' },
      { name: 'earnedValue', type: 'currency', label: 'Earned Value' },
      { name: 'description', type: 'string', label: 'Description' },
    ],
    relations: [
      { foreignKey: 'jobId', collection: 'job/job', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'project/milestone',
    module: 'project',
    version: 1,
    fields: [
      { name: 'projectId', type: 'id', required: true, label: 'Project' },
      { name: 'name', type: 'string', required: true, label: 'Milestone Name' },
      { name: 'dueDate', type: 'date', label: 'Due Date' },
      { name: 'actualDate', type: 'date', label: 'Actual Date' },
      { name: 'status', type: 'enum', enum: ['pending', 'completed', 'late'], label: 'Status' },
      { name: 'isCritical', type: 'boolean', label: 'Critical Path' },
      { name: 'description', type: 'string', label: 'Description' },
    ],
    relations: [
      { foreignKey: 'projectId', collection: 'project/project', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
  {
    collection: 'project/task',
    module: 'project',
    version: 1,
    fields: [
      { name: 'projectId', type: 'id', required: true, label: 'Project' },
      { name: 'milestoneId', type: 'id', label: 'Milestone' },
      { name: 'name', type: 'string', required: true, label: 'Task Name' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'assignee', type: 'string', label: 'Assignee' },
      { name: 'startDate', type: 'date', label: 'Start Date' },
      { name: 'endDate', type: 'date', label: 'End Date' },
      { name: 'baselineStart', type: 'date', label: 'Baseline Start' },
      { name: 'baselineEnd', type: 'date', label: 'Baseline End' },
      { name: 'duration', type: 'number', label: 'Duration (days)' },
      { name: 'actualStart', type: 'date', label: 'Actual Start' },
      { name: 'actualEnd', type: 'date', label: 'Actual End' },
      { name: 'percentComplete', type: 'number', label: 'Percent Complete' },
      { name: 'status', type: 'enum', enum: ['not_started', 'in_progress', 'completed', 'delayed'], label: 'Status' },
      { name: 'isCriticalPath', type: 'boolean', label: 'Critical Path' },
      { name: 'resourceType', type: 'enum', enum: ['labor', 'equipment', 'material'], label: 'Resource Type' },
      { name: 'budgetHours', type: 'number', label: 'Budget Hours' },
      { name: 'actualHours', type: 'number', label: 'Actual Hours' },
      { name: 'budgetCost', type: 'currency', label: 'Budget Cost' },
      { name: 'actualCost', type: 'currency', label: 'Actual Cost' },
      { name: 'sortOrder', type: 'number', label: 'Sort Order' },
    ],
    relations: [
      { foreignKey: 'projectId', collection: 'project/project', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'milestoneId', collection: 'project/milestone', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'project/taskDependency',
    module: 'project',
    version: 1,
    fields: [
      { name: 'taskId', type: 'id', required: true, label: 'Task' },
      { name: 'predecessorId', type: 'id', required: true, label: 'Predecessor' },
      { name: 'type', type: 'enum', enum: ['FS', 'FF', 'SS', 'SF'], label: 'Dependency Type' },
      { name: 'lag', type: 'number', label: 'Lag (days)' },
    ],
    relations: [
      { foreignKey: 'taskId', collection: 'project/task', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'predecessorId', collection: 'project/task', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
  {
    collection: 'project/dailyLog',
    module: 'project',
    version: 1,
    fields: [
      { name: 'projectId', type: 'id', required: true, label: 'Project' },
      { name: 'date', type: 'date', required: true, label: 'Date' },
      { name: 'weather', type: 'string', label: 'Weather Conditions' },
      { name: 'temperature', type: 'string', label: 'Temperature' },
      { name: 'crew', type: 'string', label: 'Crew' },
      { name: 'workPerformed', type: 'string', label: 'Work Performed' },
      { name: 'visitors', type: 'string', label: 'Visitors' },
      { name: 'incidents', type: 'string', label: 'Incidents' },
      { name: 'notes', type: 'string', label: 'Notes' },
      { name: 'photos', type: 'array', label: 'Photos' },
    ],
    relations: [
      { foreignKey: 'projectId', collection: 'project/project', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
  {
    collection: 'project/rfi',
    module: 'project',
    version: 1,
    fields: [
      { name: 'projectId', type: 'id', required: true, label: 'Project' },
      { name: 'number', type: 'number', required: true, label: 'RFI Number' },
      { name: 'subject', type: 'string', required: true, label: 'Subject' },
      { name: 'question', type: 'string', label: 'Question' },
      { name: 'requestedBy', type: 'string', label: 'Requested By' },
      { name: 'assignedTo', type: 'string', label: 'Assigned To' },
      { name: 'dueDate', type: 'date', label: 'Due Date' },
      { name: 'status', type: 'enum', enum: ['open', 'answered', 'closed', 'overdue'], label: 'Status' },
      { name: 'priority', type: 'enum', enum: ['low', 'medium', 'high', 'urgent'], label: 'Priority' },
      { name: 'response', type: 'string', label: 'Response' },
      { name: 'responseDate', type: 'date', label: 'Response Date' },
    ],
    relations: [
      { foreignKey: 'projectId', collection: 'project/project', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
  {
    collection: 'project/submittal',
    module: 'project',
    version: 1,
    fields: [
      { name: 'projectId', type: 'id', required: true, label: 'Project' },
      { name: 'number', type: 'number', required: true, label: 'Submittal Number' },
      { name: 'specSection', type: 'string', label: 'Spec Section' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'submittedBy', type: 'string', label: 'Submitted By' },
      { name: 'status', type: 'enum', enum: ['pending', 'approved', 'approved_as_noted', 'rejected', 'resubmit'], label: 'Status' },
      { name: 'submittedDate', type: 'date', label: 'Submitted Date' },
      { name: 'reviewedDate', type: 'date', label: 'Reviewed Date' },
      { name: 'reviewer', type: 'string', label: 'Reviewer' },
      { name: 'notes', type: 'string', label: 'Notes' },
    ],
    relations: [
      { foreignKey: 'projectId', collection: 'project/project', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
  {
    collection: 'project/meetingMinutes',
    module: 'project',
    version: 1,
    fields: [
      { name: 'projectId', type: 'id', required: true, label: 'Project' },
      { name: 'date', type: 'date', required: true, label: 'Meeting Date' },
      { name: 'type', type: 'enum', enum: ['progress', 'safety', 'owner', 'pre_construction'], label: 'Meeting Type' },
      { name: 'attendees', type: 'array', label: 'Attendees' },
      { name: 'topics', type: 'array', label: 'Topics' },
      { name: 'actionItems', type: 'array', label: 'Action Items' },
      { name: 'nextMeetingDate', type: 'date', label: 'Next Meeting Date' },
      { name: 'notes', type: 'string', label: 'Notes' },
    ],
    relations: [
      { foreignKey: 'projectId', collection: 'project/project', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
  {
    collection: 'project/weatherDelay',
    module: 'project',
    version: 1,
    fields: [
      { name: 'projectId', type: 'id', required: true, label: 'Project' },
      { name: 'date', type: 'date', required: true, label: 'Date' },
      { name: 'type', type: 'enum', enum: ['rain', 'snow', 'wind', 'extreme_heat', 'extreme_cold', 'other'], label: 'Weather Type' },
      { name: 'hoursLost', type: 'number', label: 'Hours Lost' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'impactedTasks', type: 'array', label: 'Impacted Tasks' },
    ],
    relations: [
      { foreignKey: 'projectId', collection: 'project/project', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
  {
    collection: 'project/resourceAllocation',
    module: 'project',
    version: 1,
    fields: [
      { name: 'projectId', type: 'id', required: true, label: 'Project' },
      { name: 'taskId', type: 'id', label: 'Task' },
      { name: 'resourceType', type: 'enum', enum: ['labor', 'equipment'], label: 'Resource Type' },
      { name: 'resourceId', type: 'string', label: 'Resource ID' },
      { name: 'hours', type: 'number', label: 'Hours' },
      { name: 'startDate', type: 'date', label: 'Start Date' },
      { name: 'endDate', type: 'date', label: 'End Date' },
    ],
    relations: [
      { foreignKey: 'projectId', collection: 'project/project', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'taskId', collection: 'project/task', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
];
