/**
 * Service Management module collection schemas.
 * Phase 20: serviceAgreement, workOrder, workOrderLine, serviceCall,
 * customerEquipment, preventiveMaintenance, technicianTimeEntry.
 */

import type { SchemaDef } from '../../types/schema';

export const serviceSchemas: SchemaDef[] = [
  {
    collection: 'service/serviceAgreement',
    module: 'serviceMgmt',
    version: 1,
    fields: [
      { name: 'customerId', type: 'id', required: true, label: 'Customer' },
      { name: 'name', type: 'string', required: true, label: 'Agreement Name' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'type', type: 'enum', enum: ['full_service', 'preventive', 'on_call', 'warranty'], required: true, label: 'Agreement Type' },
      { name: 'status', type: 'enum', enum: ['active', 'expired', 'cancelled', 'pending'], label: 'Status' },
      { name: 'startDate', type: 'date', required: true, label: 'Start Date' },
      { name: 'endDate', type: 'date', label: 'End Date' },
      { name: 'renewalDate', type: 'date', label: 'Renewal Date' },
      { name: 'recurringAmount', type: 'currency', label: 'Recurring Amount' },
      { name: 'billingFrequency', type: 'enum', enum: ['monthly', 'quarterly', 'annually'], label: 'Billing Frequency' },
      { name: 'terms', type: 'string', label: 'Terms' },
      { name: 'coveredEquipment', type: 'string', label: 'Covered Equipment' },
      { name: 'responseTimeSla', type: 'string', label: 'Response Time SLA' },
      { name: 'entityId', type: 'id', label: 'Entity' },
    ],
    relations: [
      { foreignKey: 'customerId', collection: 'ar/customer', type: 'belongsTo', cascade: 'restrict' },
      { foreignKey: 'entityId', collection: 'entity/entity', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'service/workOrder',
    module: 'serviceMgmt',
    version: 1,
    fields: [
      { name: 'agreementId', type: 'id', label: 'Service Agreement' },
      { name: 'customerId', type: 'id', required: true, label: 'Customer' },
      { name: 'number', type: 'string', required: true, label: 'Work Order Number' },
      { name: 'type', type: 'enum', enum: ['scheduled', 'on_demand', 'emergency', 'callback'], required: true, label: 'Type' },
      { name: 'status', type: 'enum', enum: ['open', 'assigned', 'in_progress', 'on_hold', 'completed', 'invoiced', 'cancelled'], label: 'Status' },
      { name: 'priority', type: 'enum', enum: ['low', 'medium', 'high', 'emergency'], label: 'Priority' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'assignedTo', type: 'string', label: 'Assigned To' },
      { name: 'scheduledDate', type: 'date', label: 'Scheduled Date' },
      { name: 'scheduledTimeSlot', type: 'string', label: 'Scheduled Time Slot' },
      { name: 'completedDate', type: 'date', label: 'Completed Date' },
      { name: 'customerEquipmentId', type: 'id', label: 'Customer Equipment' },
      { name: 'problemDescription', type: 'string', label: 'Problem Description' },
      { name: 'resolution', type: 'string', label: 'Resolution' },
      { name: 'laborTotal', type: 'currency', label: 'Labor Total' },
      { name: 'materialTotal', type: 'currency', label: 'Material Total' },
      { name: 'totalAmount', type: 'currency', label: 'Total Amount' },
      { name: 'pricingType', type: 'enum', enum: ['flat_rate', 'tm'], label: 'Pricing Type' },
      { name: 'flatRateAmount', type: 'currency', label: 'Flat Rate Amount' },
      { name: 'billingStatus', type: 'enum', enum: ['unbilled', 'billed', 'partial'], label: 'Billing Status' },
      { name: 'invoiceId', type: 'id', label: 'Invoice' },
      { name: 'entityId', type: 'id', label: 'Entity' },
    ],
    relations: [
      { foreignKey: 'agreementId', collection: 'service/serviceAgreement', type: 'belongsTo', cascade: 'nullify' },
      { foreignKey: 'customerId', collection: 'ar/customer', type: 'belongsTo', cascade: 'restrict' },
      { foreignKey: 'customerEquipmentId', collection: 'service/customerEquipment', type: 'belongsTo', cascade: 'nullify' },
      { foreignKey: 'entityId', collection: 'entity/entity', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'service/workOrderLine',
    module: 'serviceMgmt',
    version: 1,
    fields: [
      { name: 'workOrderId', type: 'id', required: true, label: 'Work Order' },
      { name: 'type', type: 'enum', enum: ['labor', 'material', 'other'], required: true, label: 'Line Type' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'quantity', type: 'number', required: true, label: 'Quantity' },
      { name: 'unitPrice', type: 'currency', required: true, label: 'Unit Price' },
      { name: 'amount', type: 'currency', label: 'Amount' },
      { name: 'technicianId', type: 'string', label: 'Technician' },
      { name: 'partNumber', type: 'string', label: 'Part Number' },
    ],
    relations: [
      { foreignKey: 'workOrderId', collection: 'service/workOrder', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
  {
    collection: 'service/serviceCall',
    module: 'serviceMgmt',
    version: 1,
    fields: [
      { name: 'customerId', type: 'id', required: true, label: 'Customer' },
      { name: 'workOrderId', type: 'id', label: 'Work Order' },
      { name: 'callDate', type: 'date', required: true, label: 'Call Date' },
      { name: 'callType', type: 'enum', enum: ['request', 'complaint', 'inquiry', 'emergency'], required: true, label: 'Call Type' },
      { name: 'priority', type: 'enum', enum: ['low', 'medium', 'high', 'emergency'], label: 'Priority' },
      { name: 'description', type: 'string', label: 'Description' },
      { name: 'callerName', type: 'string', label: 'Caller Name' },
      { name: 'callerPhone', type: 'string', label: 'Caller Phone' },
      { name: 'status', type: 'enum', enum: ['new', 'dispatched', 'resolved'], label: 'Status' },
      { name: 'assignedTo', type: 'string', label: 'Assigned To' },
      { name: 'dispatchedAt', type: 'date', label: 'Dispatched At' },
      { name: 'resolvedAt', type: 'date', label: 'Resolved At' },
    ],
    relations: [
      { foreignKey: 'customerId', collection: 'ar/customer', type: 'belongsTo', cascade: 'restrict' },
      { foreignKey: 'workOrderId', collection: 'service/workOrder', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'service/customerEquipment',
    module: 'serviceMgmt',
    version: 1,
    fields: [
      { name: 'customerId', type: 'id', required: true, label: 'Customer' },
      { name: 'name', type: 'string', required: true, label: 'Equipment Name' },
      { name: 'manufacturer', type: 'string', label: 'Manufacturer' },
      { name: 'model', type: 'string', label: 'Model' },
      { name: 'serialNumber', type: 'string', label: 'Serial Number' },
      { name: 'installDate', type: 'date', label: 'Install Date' },
      { name: 'warrantyEndDate', type: 'date', label: 'Warranty End Date' },
      { name: 'location', type: 'string', label: 'Location' },
      { name: 'status', type: 'enum', enum: ['active', 'inactive', 'retired'], label: 'Status' },
      { name: 'lastServiceDate', type: 'date', label: 'Last Service Date' },
      { name: 'nextServiceDate', type: 'date', label: 'Next Service Date' },
      { name: 'notes', type: 'string', label: 'Notes' },
    ],
    relations: [
      { foreignKey: 'customerId', collection: 'ar/customer', type: 'belongsTo', cascade: 'restrict' },
    ],
  },
  {
    collection: 'service/preventiveMaintenance',
    module: 'serviceMgmt',
    version: 1,
    fields: [
      { name: 'customerEquipmentId', type: 'id', required: true, label: 'Customer Equipment' },
      { name: 'agreementId', type: 'id', label: 'Service Agreement' },
      { name: 'name', type: 'string', required: true, label: 'PM Name' },
      { name: 'frequency', type: 'enum', enum: ['weekly', 'monthly', 'quarterly', 'semi_annual', 'annual'], required: true, label: 'Frequency' },
      { name: 'lastPerformed', type: 'date', label: 'Last Performed' },
      { name: 'nextDue', type: 'date', label: 'Next Due' },
      { name: 'checklist', type: 'string', label: 'Checklist' },
      { name: 'estimatedDuration', type: 'number', label: 'Estimated Duration (hours)' },
      { name: 'assignedTo', type: 'string', label: 'Assigned To' },
      { name: 'status', type: 'enum', enum: ['active', 'paused', 'completed'], label: 'Status' },
    ],
    relations: [
      { foreignKey: 'customerEquipmentId', collection: 'service/customerEquipment', type: 'belongsTo', cascade: 'cascade' },
      { foreignKey: 'agreementId', collection: 'service/serviceAgreement', type: 'belongsTo', cascade: 'nullify' },
    ],
  },
  {
    collection: 'service/technicianTimeEntry',
    module: 'serviceMgmt',
    version: 1,
    fields: [
      { name: 'workOrderId', type: 'id', required: true, label: 'Work Order' },
      { name: 'technicianId', type: 'string', required: true, label: 'Technician' },
      { name: 'date', type: 'date', required: true, label: 'Date' },
      { name: 'startTime', type: 'string', label: 'Start Time' },
      { name: 'endTime', type: 'string', label: 'End Time' },
      { name: 'hours', type: 'number', required: true, label: 'Hours' },
      { name: 'hourlyRate', type: 'currency', label: 'Hourly Rate' },
      { name: 'amount', type: 'currency', label: 'Amount' },
      { name: 'travelTime', type: 'number', label: 'Travel Time (hours)' },
      { name: 'description', type: 'string', label: 'Description' },
    ],
    relations: [
      { foreignKey: 'workOrderId', collection: 'service/workOrder', type: 'belongsTo', cascade: 'cascade' },
    ],
  },
];
