export const analyticsManifest = {
  id: 'concrete.analytics', name: 'Advanced Analytics & Business Intelligence', description: 'Drag-and-drop analytics builder, KPI library, job fade analysis, predictive modeling, benchmarks, custom dashboards, and scheduled reports.', version: '1.0.0', phase: 30, dependencies: [],
  collections: ['analytics/widget','analytics/kpi','analytics/jobFade','analytics/cashFlowModel','analytics/revenueForecast','analytics/laborProductivity','analytics/equipmentROI','analytics/vendorScore','analytics/retention','analytics/scenario','analytics/benchmark','analytics/dashboard','analytics/scheduledReport','analytics/dataExport'],
  routes: [
    { path: '/analytics/builder', component: () => import('./views/builder'), title: 'Analytics Builder', icon: 'bar-chart-2' },
    { path: '/analytics/kpi-library', component: () => import('./views/kpi-library'), title: 'KPI Library', icon: 'target' },
    { path: '/analytics/job-fade', component: () => import('./views/job-fade'), title: 'Job Fade', icon: 'trending-down' },
    { path: '/analytics/cash-flow', component: () => import('./views/cash-flow'), title: 'Cash Flow Models', icon: 'dollar-sign' },
    { path: '/analytics/revenue', component: () => import('./views/revenue'), title: 'Revenue Forecast', icon: 'trending-up' },
    { path: '/analytics/labor', component: () => import('./views/labor'), title: 'Labor Productivity', icon: 'users' },
    { path: '/analytics/equipment-roi', component: () => import('./views/equipment-roi'), title: 'Equipment ROI', icon: 'truck' },
    { path: '/analytics/vendor-scores', component: () => import('./views/vendor-scores'), title: 'Vendor Scoring', icon: 'star' },
    { path: '/analytics/retention', component: () => import('./views/retention'), title: 'Retention', icon: 'user-check' },
    { path: '/analytics/scenarios', component: () => import('./views/scenarios'), title: 'What-If', icon: 'shuffle' },
    { path: '/analytics/benchmarks', component: () => import('./views/benchmarks'), title: 'Benchmarks', icon: 'bar-chart' },
    { path: '/analytics/dashboards', component: () => import('./views/dashboards'), title: 'Dashboards', icon: 'layout' },
    { path: '/analytics/scheduled', component: () => import('./views/scheduled'), title: 'Scheduled Reports', icon: 'calendar' },
    { path: '/analytics/exports', component: () => import('./views/exports'), title: 'Data Export', icon: 'download' },
  ],
  navItems: [
    { id: 'analytics', label: 'Analytics', icon: 'bar-chart-2', path: '/analytics/builder', order: 300 },
    { id: 'an-builder', label: 'Builder', icon: 'bar-chart-2', path: '/analytics/builder', order: 1, parent: 'analytics' },
    { id: 'an-kpi', label: 'KPI Library', icon: 'target', path: '/analytics/kpi-library', order: 2, parent: 'analytics' },
    { id: 'an-fade', label: 'Job Fade', icon: 'trending-down', path: '/analytics/job-fade', order: 3, parent: 'analytics' },
    { id: 'an-cash', label: 'Cash Flow', icon: 'dollar-sign', path: '/analytics/cash-flow', order: 4, parent: 'analytics' },
    { id: 'an-rev', label: 'Revenue', icon: 'trending-up', path: '/analytics/revenue', order: 5, parent: 'analytics' },
    { id: 'an-labor', label: 'Labor', icon: 'users', path: '/analytics/labor', order: 6, parent: 'analytics' },
    { id: 'an-equip', label: 'Equipment ROI', icon: 'truck', path: '/analytics/equipment-roi', order: 7, parent: 'analytics' },
    { id: 'an-vendor', label: 'Vendors', icon: 'star', path: '/analytics/vendor-scores', order: 8, parent: 'analytics' },
    { id: 'an-ret', label: 'Retention', icon: 'user-check', path: '/analytics/retention', order: 9, parent: 'analytics' },
    { id: 'an-whatif', label: 'What-If', icon: 'shuffle', path: '/analytics/scenarios', order: 10, parent: 'analytics' },
    { id: 'an-bench', label: 'Benchmarks', icon: 'bar-chart', path: '/analytics/benchmarks', order: 11, parent: 'analytics' },
    { id: 'an-dash', label: 'Dashboards', icon: 'layout', path: '/analytics/dashboards', order: 12, parent: 'analytics' },
    { id: 'an-sched', label: 'Scheduled', icon: 'calendar', path: '/analytics/scheduled', order: 13, parent: 'analytics' },
    { id: 'an-export', label: 'Data Export', icon: 'download', path: '/analytics/exports', order: 14, parent: 'analytics' },
  ],
  dashboardWidgets: [], settings: [], permissions: [
    { resource: 'analytics.widget', actions: ['create','read','update','delete'], description: 'Analytics widgets' },
    { resource: 'analytics.kpi', actions: ['create','read','update'], description: 'KPI definitions' },
    { resource: 'analytics.dashboard', actions: ['create','read','update','delete'], description: 'Custom dashboards' },
    { resource: 'analytics.report', actions: ['create','read','update','delete'], description: 'Scheduled reports' },
    { resource: 'analytics.export', actions: ['create','read','run'], description: 'Data exports' },
  ], workflows: [], importTypes: [], exportTypes: [], hooks: [],
};
